### ISSUE TITLE
defaultConfig[mode] missing from Compare?

### ISSUE THREAD

**Issue by lamasgergo** [FriendsOfCake/search#101]
I think it's not a big deal to implement "mode" config into Compare. When you would like to compare multiple values with same field but with "OR" relation, now you can't.
For example you would like to search in a webshop for products with prices wich are stored in different coulumns.
Thanks! I love this plugin!

**Comment by ADmad** [comment]
PR to implement the enhancement is welcome.

**Comment by flangofas** [comment]
I can provide a fix :smile:

**Comment by dereuromark** [comment]
PR is open.
