### ISSUE TITLE
Form not working

### ISSUE THREAD

**Issue by tephysalazar** [FriendsOfCake/search#102]
Hey, I got the plugin working but the form does not. I need to put manually the URL and then it works. (example: .../clients?dni=123)

This is the form code 
` echo $this->Form->create();`
`echo $this->Form->input('dni');`
`echo $this->Form->button('Filter', ['type' => 'submit']);`
`echo $this->Html->link('Reset', ['action' => 'index']);`
`echo $this->Form->end();`

**Comment by ADmad** [comment]
You probably forgot to load the `Prg` component in your controller.
