### ISSUE TITLE
Bug: aliasField is run twice for some Filter rules

### ISSUE THREAD

**Issue by htstudios** [FriendsOfCake/search#111]
Result is that the built query may look like this: `Countries.Countries.code IN (:c0)`

E.g. for Search.Like it is not, as like uses `Base::fields()` which extract out of `(array)$this->config('field')`
However for `Search.Value` it is being reapplied.

E.g. a setup like this
```
$this->searchManager()
    ->add($this->aliasField('code'), 'Search.Value', [
        'before' => true,
        'after' => true,
    ])
    ->add($this->aliasField('label'), 'Search.Like', [
        'before' => true,
        'after' => true,
    ])
```

Fails at the first `add()` call. When adding `'field' => $this->aliasField('code')` it works again.
Thus:

EITHER `Base::field()` should be taught to only apply the alias/table name if not yet applied. Then `Base::fields()` should be made to work like `Base::field()` so that Search.Like works like the rest
OR Search.Value and all the others should work like Search.Like.

**Comment by jippi** [comment]
Not a bug, fields are automatically passed through `aliasField` - use `aliasField => false` to disable this behavior for each `field`

**Comment by htstudios** [comment]
So why are the fields for Search.Like not passed through aliasField() - or where are they being passed?

**Comment by jippi** [comment]
they should be 

It calls 
- https://github.com/FriendsOfCake/search/blob/master/src/Model/Filter/Like.php#L33
- https://github.com/FriendsOfCake/search/blob/master/src/Model/Filter/Base.php#L115
- https://github.com/FriendsOfCake/search/blob/master/src/Model/Filter/Base.php#L87
- https://github.com/FriendsOfCake/search/blob/master/src/Model/Filter/Base.php#L99-L107

**Comment by ADmad** [comment]
In version 2 of the plugin fields are auto aliased so don't alias them in your search config.

**Comment by ADmad** [comment]
Or set `aliasField` option to false in filter config to disable auto aliasing.

**Comment by htstudios** [comment]
@jippi Okay, that got patched in https://github.com/FriendsOfCake/search/commit/236e9abb6754820462313f97d6dbadcd3f44c2bb

@ADmad Only with 2.0.1 it seems to have been fixed, not with 2.0
However when I do `$ composer require friendsofcake/search` I always get a code base that has
```php
    /**
     * Get the database field name(s) as an array.
     *
     * @return array
     */
    public function fields()
    {
        return (array)$this->config('field');
    }
```

**Comment by dereuromark** [comment]
That's because it is not part of 2.0.1.
Those changes are yet untagged, as you can find out going to releases page :)
https://github.com/FriendsOfCake/search/compare/2.0.1...master

**Comment by ADmad** [comment]
I have made a new release, wait a while until packagist catches up and update.

**Comment by htstudios** [comment]
@ADmad thank you very much! <3
