### ISSUE TITLE
Documentation unclear about "Filters"

### ISSUE THREAD

**Issue by powtac** [FriendsOfCake/search#115]
When reading through https://github.com/FriendsOfCake/search#filters I do not understand where I can "activate" or use those mentioned filters. 

Is it `->add('active', 'Search.Boolean')` to use a boolean Filter on the "active" field? (That syntax seems not to work and I still don't know where to activate it.)

**Comment by burzum** [comment]
Define "not to work" and show your code. :)

The filter itself is well covered with tests -> https://github.com/FriendsOfCake/search/blob/master/tests/TestCase/Model/Filter/BooleanTest.php

**Comment by powtac** [comment]
Ok, I figured it out:

```
            ->add('success', 'Search.Boolean', [
                'mode'			=> 'and',
                'field'			=> 'success' // This works! This not: 'field' => ['success']
            ])   
```

`field`  can not be an array in case of Boolean! Seems like a documentation issue.

**Comment by burzum** [comment]
Besides that I think it should throw an Exception as well if an invalid arg is passed.

**Comment by inoas** [comment]
Can you give it a try and change
https://github.com/FriendsOfCake/search/blob/master/src/Model/Filter/Boolean.php#L37
from:

```php
    $this->query()->andWhere([$this->field() => $bool]);
```

to:

```
foreach ((array) $this->field() as $field) {
    $this->query()->andWhere([$field => $bool]);
}
```

If it works I will see if the tests are okay with it and create a PR.

**Comment by ADmad** [comment]
Some filters can take multiple fields and hence an array while some only take a single once hence a string.

**Comment by powtac** [comment]
@inoas 
`->add('active', 'Search.Boolean')` does work. 
`->add('active', 'Search.Boolean', ['field' => ['active']])` does not work.

**Comment by burzum** [comment]
I agree with @powtac that the API is not very intuitive and his example is pretty confusing. I wouldn't expect this behavior, it just doesn't make sense if you looked at the other filters before.

Filters should fail hard (Exception) if you don't configure them right.

**Comment by ADmad** [comment]
In general most FOC plugins are a bit lacking when it comes to documentation. We need the community's help to improve that :smile:

**Comment by dereuromark** [comment]
One should think that with such a large community base those would be way better documented than any of those single-person ones out there.. ;) well well

**Comment by burzum** [comment]
@dereuromark well, forget it. :) My personal experience is that 99% of the people just take and a fraction of them is even as bold to *demand* things to be done ASAP and for free. Neither for the CakeDC nor for my own plugins I've ever seen much community contribution, especially when it comes to documentation.

**Comment by inoas** [comment]
I don't have a problem adding array support. It should not be expected to do magic like being able to do AND OR XOR etc... but it would be able to simply check two fields. That would also get it in line if you supplied an array. However I find the hashKey "field" to point at singular.

So in case you want me to act @ADmad let me know, else I will shut-up.

@powtac Would you care to create a PR to the docs to explain that it only takes a single string?

**Comment by powtac** [comment]
@inoas sure. _But still I'm not sure where so check in the source code to find what config is actually supported. https://github.com/FriendsOfCake/search/blob/dd370c8782cb56f1b3d33006ba8296208d0e5eba/src/Model/Filter/Base.php#L59 does not tell much about array/not array._
