### ISSUE TITLE
SearchBehavior unable to use non default filters collection.

### ISSUE THREAD

**Issue by ADmad** [FriendsOfCake/search#117]
The `SearchManager` has the ability to maintain multiple filter collections. For e.g. you can have separate collections for backend and frontend. But when using the search finder there's no way to tell it to which collection to use. It always uses the "default" collection.

The fix seems easy enough. Just allow passing a `collection` key to finder options and update the behavior to use `SearchBehavior::getFilters()` passing in the collection name instead of calling `SearchBehavior::all()` which always returns the default collection.

**Comment by flangofas** [comment]
I will provide a fix for this one.

**Comment by ADmad** [comment]
@flangofas Great! Don't forget tests :)
