### ISSUE TITLE
View Question

### ISSUE THREAD

**Issue by fiveninesixtwosix** [FriendsOfCake/search#122]
Hello!

Not an issue but more of a newbie CakePHP 3.x question. How do I pass the search results to another view? Let's say, I have the search form on my index.ctp and want the results to display on search.ctp view.

Thanks,
Lyman

**Comment by inoas** [comment]
This is not a help forum.
I suggest you try #cakephp on Freenode IRC.
As a hint, the links you are generating need to take over `'?' => $this->request->query`
