### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by ADmad** [FriendsOfCake/search#123]
Would be nice to get test coverage in the 90s, currently it's around 82%. Contributions from the community welcome.

**Comment by dereuromark** [comment]
Especially Finder.php has 0% coverage so far: https://codecov.io/gh/FriendsOfCake/search/src/82818bd853f2f06cb64298af5f52546c88686360/src/Model/Filter/Finder.php

**Comment by flangofas** [comment]
@ADmad Sure.

**Comment by ADmad** [comment]
#129 has brought up the coverage to 100%!  Thanks for offering to help @flangofas. There's #101 if you want to help some more :)

**Comment by bravo-kernel** [comment]
👏🏼

**Comment by flangofas** [comment]
@ADmad beautiful :+1:
