### ISSUE TITLE
Multiselect parameters are ignored

### ISSUE THREAD

**Issue by ryo2** [FriendsOfCake/search#124]
#113  seems to cause a problem with multiselect parameters.

ex.
http://example.ex/search?type[]=1&type[]=2
`Hash::flatten($params)` makes $params like `['type.0' => 1, 'type.1' => 2]`.
Then `array_intersect_key` remove them and they are ignored.

**Comment by dereuromark** [comment]
What would be the $params be without the Hash::flatten() part?

**Comment by ADmad** [comment]
Trying to fix this would involve introspecting the filters configured to figure out which keys need to be flattened and which not. I am not sure that can be achieved in a foolproof way and even if there were it would involve significant code complexity, which I wouldn't want to add to this plugin.

So IMO it's best to just revert the changes done in #113.

**Comment by dereuromark** [comment]
Or add an opt-in option "flatten" which defaults to false for BC reasons?

**Comment by inoas** [comment]
@ryo2 can you take a look at making the flattener an opt-out or opt-in option?
I can get to this next weekend (ping me if I forget to do it).

**Comment by ADmad** [comment]
I am not a fan of adding features which only work in special cases. Most users won't be aware of the circumstances in which they can/cannot use it and we end up getting bug reports.

**Comment by inoas** [comment]
@ADmad we can make it an opt-in feature. No Problem. Without the feature scoped searches don't work. Pagination works with scopes now. So this is expected to work as well.
Another way would be not not use Hash::flatten but custom code for the transformation of the arrays to dotnotation.

**Comment by dereuromark** [comment]
One problem could be that people might rely on the 2.1.0 behavior, providing an option to quickly opt-in might make it easier for them to continue using that major version.
A custom flatten option might be the even better option if possible.

**Comment by ADmad** [comment]
I guess making it optional is the least path of resistance. So I am ok with making this an opt-in feature. A `flattenParams` option can be added to `SearchBehavior` with default `false`.

**Comment by ADmad** [comment]
#126 addresses this without requiring to add a new option.

**Comment by inoas** [comment]
@ryo2 Let me know if #126 solves your use cases.

**Comment by ryo2** [comment]
@inoas #126 will solve my case and might be better solution for this IMO.
