### ISSUE TITLE
Search.Like: Array to string conversion [CORE/src/Database/Expression/Comparison.php, line 165]

### ISSUE THREAD

**Issue by holisticnetworking** [FriendsOfCake/search#134]
Not sure what's going on, but here is my Search Manager config for this value:

`->add('institution', 'Search.Value', [
	'field' => ['institution_id']
]);`

Not getting this error anywhere else on the system, and I'm using your search quite a bit. This seems to exclusively be a problem with the Search.Value filter. Maybe I'm calling it wrong, but there's not a lot of documentation to correct myself.

**Comment by ADmad** [comment]
For `Value` filter `field` needs to be a string not array.
