### ISSUE TITLE
Failed to open stream issue

### ISSUE THREAD

**Issue by clementcrownrise** [FriendsOfCake/search#140]
Hello, I just installed this search plugin and did all the required configuration but on going back to my website, I got this error
![image](https://cloud.githubusercontent.com/assets/3583726/21193129/6fca752a-c22b-11e6-9b64-9520ad31dbc1.png)

Please how can i fix it? I installed the plugin with composer.

Thanks for your help

**Comment by ADmad** [comment]
What does your `Plugin::load()` command look like?

**Comment by clementcrownrise** [comment]
thanks 2 ADmad, you called my attention to it, the autoload was not set to "True".

I have set it to "True " and the error is no more.

Thanks

**Comment by clementcrownrise** [comment]
@ ADmad, but the search doesnt seem to work
