### ISSUE TITLE
Postgres and CI lookup

### ISSUE THREAD

**Issue by dereuromark** [FriendsOfCake/search#144]
There is LIKE vs ILIKE for the wildcard lookup, but for value I dont see anything in https://github.com/FriendsOfCake/search/blob/master/src/Model/Filter/Value.php

Can we introduce a way to allow case insensitive (CI) lookup for such text strings?
By default it uses the underlying DB specification, sure, for MySQL you can specify that using _ci or _cs collations. But for Postgres it's CS by default.

Having an option seems useful, which would internally then UPPER() = UPPER() or something.
Not sure what the Cake ORM internally can already do maybe.

Proposed option key:

    'caseInsensitive' => false 

(defaults to false for BC, and is only needed for some DB types)

**Comment by bravo-kernel** [comment]
This would be more than welcome as the crud-json-api CI tests now fail on Postgres CS search

**Comment by ADmad** [comment]
Btw using `citex` looks like the easiest option: https://www.postgresql.org/docs/9.3/static/citext.html

**Comment by ADmad** [comment]
Closing as this can be easily achieved by setting up the column for case insensitive matching at db level.

`citex` for Postgres and `*_ci` collation for MySQL.

**Comment by dereuromark** [comment]
Hm, the problem with these is that they are too low levvel for all use cases.
In some cases you just need it for a specific search filter, not more globally..
