### ISSUE TITLE
Search + Pagination [Cake\Network\Exception\NotFoundException] 

### ISSUE THREAD

**Issue by dilab** [FriendsOfCake/search#147]
## Replicate 

1. Navigate to page 2 of current search result page
2. Enter some search query to the search box
3. It throws [Cake\Network\Exception\NotFoundException]  because it tries to access an invalid page. 
``` ?page=2&search=my-search-string ```

## Suggest
Should reset the page=1 if a search is about to happen?

**Comment by jippi** [comment]
PR welcome

**Comment by ADmad** [comment]
@dilab Which version of the plugin are you using?  I tested with the latest version and using the PrgComponent the `page` param is removed when you do a new search post.

**Comment by dereuromark** [comment]
Also cannot reproduce.
