### ISSUE TITLE
Custom reusable filters

### ISSUE THREAD

**Issue by blieb** [FriendsOfCake/search#157]
Hi,

I'm searching a way to create custom filters which I can reuse in different models. Is there a good way to do this? Or is it maybe a good idea to add this feature?

at the moment it is only possible to create a callback. I don't see a way to call a custom class for filters.

**Comment by blieb** [comment]
Maybe I'm a little bit to fast creating an issue, Looking inside the code now I see this:

https://github.com/FriendsOfCake/search/blob/master/src/Manager.php#L231

think it is already possible, going to try it now, but missing in docs?

**Comment by ADmad** [comment]
Creating and using custom filters is already possible. You arr welcome to update the docs onve you figure oit how :)

**Comment by blieb** [comment]
@ADmad yes got it working. Just create a class in folder Model/Filter/YourFilter.php with content:

```
<?php
namespace App\Model\Filter;

class YourFilter extends \Search\Model\Filter\Base
{
    /**
     * Check if a value is truthy/falsy and pass as condition.
     *
     * @return void
     */
    public function process()
    {
        if ($this->skip()) {
            return;
        }

        $this->query()->andWhere([$this->field() => $this->value()]);
     }
}
```

and after that you can just add it via session manager. 

`$this->searchManager()->add('myFilter', 'App.YourFilter', ['someConfig' => 1]);`

I will check if I can write some documentation for it. :)

**Comment by dereuromark** [comment]
@blieb A small docs note sounds great.
