### ISSUE TITLE
Search forms generator

### ISSUE THREAD

**Issue by champidead** [FriendsOfCake/search#169]
Hi and thanks for all of your CakePHP plugins.

I'm wondering why this plugin cannot automatically generate the search forms based on the table fields.

You have great plugins like crud and crud-view where users don't have to do much to generate a full app but here we have to describe each field in order to generate a search form.

Thanks.

**Comment by davidyell** [comment]
In most cases, you do not want to expose your table schema to users via the url.

**Comment by dereuromark** [comment]
You could probably build a crud-search kind of plugin, that could by default read from the schema, but can easily be filtered/customized using some sort of whitelist in the table or sth.
But this is probably out of scope of this plugin here.

**Comment by curtisgibby** [comment]
I built a quick-and-dirty search form helper and submitted a PR for it #29 , but I didn't include any tests and there were various other arguments against it, so it never got merged. You could look at my version and see how it works for you. I just had to update it for #175, but it's very close to the original code.

**Comment by dereuromark** [comment]
Closing as project specific.
