### ISSUE TITLE
Callback & Finder don't handle value passed if it is a keyed array

### ISSUE THREAD

**Issue by JayWalker512** [FriendsOfCake/search#170]
I'll start with an example of what works and what doesn't because it will make what I'm trying to do a little clearer:

This example shows the current behavior which works:
```php

//request data contains an array like this from a multi-select field
$requestData = [
    'sp_id' => [
        0 => '123',
        1 => '456'
    ]
];

//filter setup
$this->searchManager()->add('sp_id', 'Search.Callback', [
    'callback' => function ($query, $args, $filter) {
        //execution get's here, all is well, I can process the array in $args
    }
]);
```

The following DOESN'T work, but it's what I'm trying to do
```php

//request data contains a keyed array from a date-select field
$requestData = [
    'start_date' => [
        'year' => '2014',
        'month' => '01',
        'day' => '13'
    ]
];

//filter setup
$this->searchManager()->add('start_date', 'Search.Callback', [
    'callback' => function ($query, $args, $filter) {
        //execution NEVER gets here, the array is totally ignored!
    }
]);
```

In the above examples I would expect each scenario to behave the same way; to pass along the array to my callback or finder and let me deal with parsing the data. However the second situation doesn't work at all, my callback or finder are never called if the value is a keyed array.

I'm trying to make a filter to narrow some rows down by date, and the second example shows how my form gives the data.

**Comment by ADmad** [comment]
The problem is being caused by the [search params flattening](https://github.com/FriendsOfCake/search/blob/master/src/Model/Behavior/SearchBehavior.php#L127) that is done by behavior.

Once way to fix the issue would be add a whitelist of params keys that should not be flattened.

**Comment by JayWalker512** [comment]
Ah yes, thank you for pointing that out! I'll see if I can post a nice solution here in a few days.
