### ISSUE TITLE
custom finder on two inputs

### ISSUE THREAD

**Issue by arilia** [FriendsOfCake/search#181]
I guess this is an enhancement but maybe it is already feasible. So far I didn't manage to find a way

I have a custom finder that needs two parameters. In my form I have two inputs. But in order to make it work I have to 'attach' the finder to both the input otherwise the value is not evaluated

This is an example

    ->add('field_1', 'Search.Finder', [
        'finder' => 'myFinder' 
    ])->add('field_2', 'Search.Finder', [
        'finder' => 'myFinder' 
    ]);

The above code works but the generated query contains two times the same conditions

The other workaround I found is to use an empty callback

    ->add('field_1', 'Search.Finder', [
        'finder' => 'myFinder' 
    ])->add('field_2', 'Search.Callback', [
        'callback' => function ($query, $args, $filter) {
        }
    ]);

I would like to do something like

    ->add([field_1', 'field_2'], 'Search.Finder', [
        'finder' => 'myFinder' 
    ]);

(My actual situation is that I have a `group_id` field and a `find_in_subgroups` flag. When I flag `find_in_subgroups` my custom finder scans for the `group_id` and for its subgroups, otherwise it just look for the exact group_id)

**Comment by dereuromark** [comment]
Are you able to provide a PR with your suggested changes?

**Comment by burzum** [comment]
@arilia can you do that as a PR with tests?

**Comment by arilia** [comment]
@burzum, sorry, but I don't think I am very good at that

**Comment by ADmad** [comment]
Closing as the issue has gone stable and no one seems interested in implementing the requested feature.
