### ISSUE TITLE
Can't get multiValue to work

### ISSUE THREAD

**Issue by LDSign** [FriendsOfCake/search#182]
Hi

I try to make a "big" search using only one input field for the query. Consider there are 2 people (firstname and lastname fields)

abc xyz
def xyz

So searching for "abc" should bring up the first person, searching for "xyz" both and "abc xyz" only the first again.

Ive tried all possible combinations of "multiValue", "fieldMode", "valueMode", "filterEmpty" in the like filter. The result is not as expected. The query should be set as an array with each search word, right? Or does the plugin split the string at the space automatically?

Is the search behaviour described above possible with this plugin and how to set up the options for this?

Thanks,
Frank

**Comment by davidyell** [comment]
Sounds like a job for a custom finder filter to me.

**Comment by dereuromark** [comment]
Custom finder it is.
