### ISSUE TITLE
Differentiate isSearch() with alwaysRun filters

### ISSUE THREAD

**Issue by raul338** [FriendsOfCake/search#186]
I would be useful to be able to discard filters with `alwaysRun` enabled when calling `isSearch()` or discard by default.
Because if you call `isSearch()` it will return true even if no other filter was used.

If you agree I could open a PR although maybe I would need help with tests

**Comment by dereuromark** [comment]
if you have an idea here that would be most welcome as PR.

**Comment by dereuromark** [comment]
By the way: Didn't I already implement exactly that with process() to always return

    @return bool True if processed, false if skipped

This way, each filter just returns false if it does not apply anything, even and especially if run in alwaysRun mode.
So IMO this is all done already, please confirm with latest v4.

**Comment by raul338** [comment]
I'm using 4.0.1 with a "history" filter that filters closes/open records, isSearch always return true

**Comment by dereuromark** [comment]
Can you show the details of the filter code, the process() part specifically?
That will help narrow down the reason it returns true where it should return false.

**Comment by raul338** [comment]
Sure, my behavior loads the filter like this
```php
$searchKey = $this->getConfig('searchKey');
$manager->callback($searchKey, [
    'alwaysRun' => true,
    'callback' => function (Query $query, $args, $manager) use ($searchKey) {
        $args += [$searchKey => 0];
        $query->find($args[$searchKey] ? 'closed' : 'open');
    },
]);
```

**Comment by dereuromark** [comment]
I think your callback must also return bool in order to work as expected. Just return false if it is not applying a filter.

**Comment by raul338** [comment]
No, adding a `return false` is still making isSearch() true

**Comment by dereuromark** [comment]
I see why: https://github.com/FriendsOfCake/search/blob/master/src/Model/Filter/Callback.php#L14
you need to check for the result here

Just add a

    if ($result === false) return false

in there

**Comment by dereuromark** [comment]
Ideally we also add a test case for it and fix up some better docs for this use case for others to more easily adapt to this.

**Comment by raul338** [comment]
PR openend
