### ISSUE TITLE
Search multiple values in multiple db fields?

### ISSUE THREAD

**Issue by salines** [FriendsOfCake/search#187]
I have one input field ‘q‘ where enter one or more keywords (q=frankfurt+de) to search in three db fields (name, city, country)., where frankfurt is city and de is country code.

    $this->searchManager()
         ->value('q')
         ->add('q', 'Search.Like', [
             'before' => true,
             'after' => true,
             'multiValue' => true,
             'fieldMode' => 'OR',
             //'valueMode' =>OR',
             //'mode'=>'OR',
             'comparison' => 'LIKE',
             'wildcardAny' => '*',
             'wildcardOne' => '?',
             'field' => ['name', 'city','country']
         ]);

  }

This produce sql query like:

```
FROM 
  `companies` `Companies` 
WHERE 
  (
    `Companies`.`name` like '%frankfurt de%' 
    OR `Companies`.`city` like '%frankfurt de%' 
    OR `Companies`.`country` like '%frankfurt de%'
  )  
```

How to setup this plugin to produce right sql query, to find multiple keywords in multiple db fields?

**Comment by dereuromark** [comment]
What exactly is your issue?
Please only open concrete issues of bug or enhancement topics.
All questions and usage help should be addressed in the help forums of CakePHP or Slack channel etc.

**Comment by salines** [comment]
OK, update issue, i can‘t find in documentation "How to setup this plugin to produce right sql query, to find multiple keywords in multiple db fields".

**Comment by dereuromark** [comment]
So what is the expected query you want to get?
Currently there is no filter yet to explode the search query string afaik to support multiple keywords like this. Correct me if I am wrong.

**Comment by salines** [comment]
You are correct. I add
```
        if(isset($this->request->query['q'])){
          $this->request->query['q'] = explode(" ", $this->request->query['q']);
        }
```
and this work.

**Comment by ADmad** [comment]
Closing and you have figured out an easy way to achieve what you need.

**Comment by dereuromark** [comment]
By the way: If you feel like there should be a filter option or sth you can always open a PR for further discussion.
