### ISSUE TITLE
i have a problem when i upload my proyect to one hosting 

### ISSUE THREAD

**Issue by MaximillianFernandez** [FriendsOfCake/search#190]
well y upload my proyect to my hosting and search is not work i dont know for what i use FilleZilla and up all my proyect please help me T_T if you have one idea about this problem

**Comment by MaximillianFernandez** [comment]
in my pc works fine but in hosting not :/

**Comment by ADmad** [comment]
Well you need to figure out yourself. We can't help you unless you can providing details showing it's a bug with the plugin itself.
