### ISSUE TITLE
This will remove boolean values

### ISSUE THREAD

**Issue by dilab** [FriendsOfCake/search#191]
https://github.com/FriendsOfCake/search/blob/a836be3000be12aadcb75c6305b85ac278e89a78/src/Model/Behavior/SearchBehavior.php#L104

The problematic piece is `Hash::filter($params)`, it will remove pair with **false** as its value. Which is not desired, because $params['key'] = false is a valid filter value

**Comment by ADmad** [comment]
Normally request's query string is passed as search params and hence are always going to be string values.

**Comment by inoas** [comment]
So using search for, say, a JSON API is out of question?

**Comment by ADmad** [comment]
A patch to allow valid non empty, non string values is welcome.

**Comment by dilab** [comment]
@inoas same here. I am using search in an API end point.

**Comment by dilab** [comment]
@ADmad PR done at https://github.com/FriendsOfCake/search/pull/193

**Comment by inoas** [comment]
This should get you going if you want to start a PR just allowing `false`:

```php
$data = ['nested' =>
    false,
    null,
    '0',
    '0.0',
    0,
    0.0,
    true,
    ' ',
]];

$filterFn = function($var) {
    return $var === 0 || $var === 0.0 || $var === '0' || $var === false || $var === null || !empty($var);
};

$res = \Cake\Utility\Hash::filter($data, $filterFn);
var_dump($res);
```

However I assume then filter doesn't make any sense if false AND null are allowed.

@ADmad would it be okay to make searchManager not filter at all? `array_intersect_key()` should be good enough/the relevant thing.

If not, would it be a good option (then disabled by default)?

https://github.com/FriendsOfCake/search/blob/a836be3000be12aadcb75c6305b85ac278e89a78/src/Model/Behavior/SearchBehavior.php#L64

Would become an option (array_intersect would happen anyway).

**Comment by dereuromark** [comment]
@inoas You should probably comment on the existing PR: https://github.com/FriendsOfCake/search/pull/193
