### ISSUE TITLE
Documentation not clear about implementation of finder

### ISSUE THREAD

**Issue by Bird87ZA** [FriendsOfCake/search#195]
The documentation is very unclear about the implementation of a custom finder.

My code looks like this:

```
class EmployeesTable extends Table
{
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->addBehavior('Search.Search');

        $this->searchManager()
            ->value('search')
            ->add('search', 'Search.Like', [
                'before' => true,
                'after' => true,
                'multiValue' => true,
                'field' => ['name', 'surname']
            ])->add('search', 'Search.Finder', [
                'finder' => 'currentlyEmployed'
            ]);
    }

    public function findCurrentlyEmployed(Query $query, array $options)
    {
        return $query->where(['Employees.status IN ' => ['Fixed Term','Full Time','Students']])
            ->order(['Employees.name' => 'ASC', 'Employees.surname' => 'ASC']);
    }
}
```

Looking at the docs, I have no idea where to even start looking for the problem.

I have the search finder in my index action like so:

    /**
     * @return Response|void
     */
    public function index()
    {
        $employees = $this->Employees->find('search', ['search' => $this->request->getQuery()]);
        $this->set('employees', $this->paginate($employees));
    }

When no search is specified it returns all the rows on the DB, and when I search for a row that should not be returned, it returns all the rows in the DB that matches the finder.

How can I fix this?

**Comment by ADmad** [comment]
The `Finder` filter requires nothing more besides specifying the finder to use by setting the `finder` key which is mentioned in readme. Regarding creating actual custom finder check the CakePHP manual.

By the way in your code examples you are using the filter name `'search'` multiple times. Each filter should be configured with a unique name.

**Comment by Bird87ZA** [comment]
I've updated the code to this:

        $this->searchManager()
            ->value('search')
            ->add('search', 'Search.Like', [
                'before' => true,
                'after' => true,
                'multiValue' => true,
                'field' => ['name', 'surname']
            ])
            ->add('finder', 'Search.Finder', [
                'finder' => 'currentlyEmployed'
            ]);

However, the same issue occurs.

If I use that finder directly in my controller, it returns the correct result. But using it with search, doesn't.

**Comment by ADmad** [comment]
What does your request url look like? Does the query string have variable "filter" with some value?

**Comment by Bird87ZA** [comment]
My request URL looks like this:

    http://local.server.com/delta-intraweb/employees?search=albert

It returns all users with name/surname containing albert. It just doesn't listen to the custom finder (meaning, in the result set, some of the employees returned is not employed anymore)

I'm not sure what you mean with query string? How would I get that?

**Comment by ADmad** [comment]
You have used name `'finder'` for the `Finder` filter, so you need to use `http://local.server.com/delta-intraweb/employees?filter=albert`.

For more assistance use the cakephp support forum or IRC or Slack channel. This issue tracker is not a support forum.

**Comment by Bird87ZA** [comment]
Your suggestion still doesn't work. So it means something with the plugin is wrong. Have you tested it recently? Can you give me a working sample? I'll join the IRC channel, however, I still feel that the documentation is lacking here as I still can't get this to work, and I've followed the docs

**Comment by Bird87ZA** [comment]
It seems like it's one or the other. You can't combine a search with a custom finder.

**Comment by davidyell** [comment]
```php
->add('finder', 'Search.Finder', [
            'finder' => 'currentlyEmployed'
        ]);
```

You're attaching the finder to a query string called `finder`, if this field isn't in your query string it will not work.

**Comment by Bird87ZA** [comment]
So how would my request url look like? If I want the search to search while including the custom finder?

**Comment by hmic** [comment]
You do want to use a finder, and add search on top of that. This is not in your request url, as it's not related to search:

```
$table->find('currentlyEmployed')->find('search', ['search' => $this->request->getQuery()]);
```

**Comment by Bird87ZA** [comment]
Thanks for copying the response I posted in the Slack chat.

**Comment by hmic** [comment]
Just to make sure: this is the correct answer.

No copyright infringement taken, I've typed it up myself.
Welcome.

Legal disclaimer:
I'm not involved with CakePHP, FriendsOfCake, or any legal entity involved with the projects, nor a member of the projects or related open source projects whatsoever. This is my personal opinion alone.

Thanks again.
Good you come up with things that are not well documented or hard to get but you might consider asking a question that is helpful to understand the problem too. And please don't bully people from the community like @davidyell for not wanting to do a one on one chat with you to solve your problem for free on his own time...
