### ISSUE TITLE
HOW USE BETWEEN Operator

### ISSUE THREAD

**Issue by samqueiroz** [FriendsOfCake/search#202]
How to use the BETWEEN operator in the plugin ?

  $this->addBehavior('Search.Search');
        $this->searchManager() 
.......

  ->add('foo', 'Search.Callback', [
                'callback' => function ($query, $args, $manager) {
                    // Modify $query as required
                }
            ]);

**Comment by ADmad** [comment]
This is a bug tracker, not a help forum. You can check the CakePHP manual or ask on one of the help forums on how to generate a query with `BETWEEN`.
