### ISSUE TITLE
Search helper for resetUrl?

### ISSUE THREAD

**Issue by dereuromark** [FriendsOfCake/search#206]
Would it make sense to add a small helper with a reset button functionality - or at least the url generation part of it?
Currently one would either end up with this multiple times, or need his own project level helper:

```php
if (!empty($_isSearch)) {
	echo $this->Html->link(__('Reset'), ['?' => array_intersect_key($this->request->query, array_flip(['sort', 'direction']))], ['class' => 'btn btn-default']);
}
```

The reset should reset the filter on paginations, but it shouldnt reset the order IMO.
See http://sandbox.dereuromark.de/sandbox/search-examples/table?search=A&sort=iso2&direction=asc

We could provide
```php
public function resetUrl(array $whitelist = []) 
{
    $whitelist += $this->config('whitelist');

    return ['?' => array_intersect_key($this->request->query, array_flip($whitelist));
}
```

**Comment by ADmad** [comment]
Your proposed `resetUrl()` is pretty generic and has no code related to the search filters. If we were to provide such a method it would make lot more sense to have one which removes the applied filters from query string. That could possibly be achieved by making `SearchBehavior::$_isSearch` (or add a new property) which maintains the list of names of filters applied.

**Comment by dereuromark** [comment]
True, currently it would be very generic and "fit" by default only to a generic use case of core Paginator.

Some `isSearch` could indeed track the fields as array (fieldName, fieldName2, ...) which would then make it possible to extract those from the query string generated in this new SearchHelper.
