### ISSUE TITLE
Installing using composer is resulting in Missing Plugin

### ISSUE THREAD

**Issue by davidspeijer** [FriendsOfCake/search#211]
I installed the plugin using composer:
`composer require friendsofcake/search`

```
Using version ^4.2 for friendsofcake/search
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing friendsofcake/search (4.2.1): Downloading (100%)
Writing lock file
Generating autoload files
> Cake\Composer\Installer\PluginInstaller::postAutoloadDump
```
Files are loaded in `/vendor/friendsofcake/search`

bootstrap.php is added with
`Plugin::load('search');`

Thereafter I receive the error

> Missing Plugin Cake\Core\Exception\MissingPluginException
> 
> Error: The application is trying to load a file from the search plugin.
> Make sure your plugin search is in the /home/rrr/domains/yourdomain.tld/public_html/timing/plugins/ directory and was loaded.
> 

Copying the files from `/vendor/friendsofcake/search` to `/plugins/search` is solving the issue, however I assume that the composer install to /vendor should be working?

I'm working in the latest version of Cake + PHP 7

**Comment by ADmad** [comment]
It's supposed to be `Plugin::load('Search');` not `Plugin::load('search');`
