### ISSUE TITLE
BS3 vs BS4 version compatibility of the plugin

### ISSUE THREAD

**Issue by burzum** [FriendsOfCake/search#213]
We're in the situation that we have a frontend and a backend. For the backend we've done a theme that will be shared between at least three different management applications we use internally and we want to use BS4 for it.

The issue with that is now that our public website is still using BS3 for the frontend and we don't have any plans to re-work that any time soon, it works and there are more pressing things to be done. By a quick test it seems that the develop branch still works with BS3 but of course I think there is no guarantee it won't break at some point.

 * Could the next version of the plugin support BS3 AND BS4?
 * Would you consider to create a new repository for a BS4 version so we can install and use both versions?
 * Any other solution?

**Comment by inoas** [comment]
Why do you want to integrate that anyway? Just override the templates or make them configurable and either have agnostic templates out of the box or BS4 onces (BS3 is now obsolete)?

**Comment by ADmad** [comment]
This issue was moved to FriendsOfCake/bootstrap-ui#212
