### ISSUE TITLE
"Like" search for integer primary column

### ISSUE THREAD

**Issue by dmromanov** [FriendsOfCake/search#218]
"LIKE" search does not work for Integer Primary columns.

## Environment
CakePHP 3.6.2
Search Plugin 4.4.0

## Sample code
DomainsTable
```php
    /**
     * @return Manager
     */
    public function searchManager(): Manager
    {
        $searchManager = $this->behaviors()->Search->searchManager();
        /** @var Manager $searchManager */
        $searchManager
            ->like('id', [
                'before' => true,
                'after' => true,
                'filterEmpty' => true,
            ]);

        return $searchManager;
    }
```

## Expected
Searching by term "85" resulting in the following filtering query.
```
  ) 
WHERE 
  (
    Domains.id like '%85%' 
  ) 
```

## Actual result
Instead I get the following
```
  ) 
WHERE 
  (
    Domains.id like 0 
  ) 
```

Might be related to #131

**Comment by dereuromark** [comment]
See https://github.com/FriendsOfCake/search/pull/152
maybe the docs need improving?

**Comment by dmromanov** [comment]
@dereuromark Thanks!

At first I specified a column type like this, and it did not work:
```php
->like('id', [
    'before' => true,
    'after' => true,
    'filterEmpty' => true,
    'colType' => ['string'],
])
```

After digging more about it I found that the `colType` attribute should be defined like this to work:
```php
'colType' => [
    'id' => 'string',
],
```

Not sure if this is working as expected but, does duplication of the column identifier really necessary?
It would be helpful if there would be an example on colType in the readme :)

**Comment by dereuromark** [comment]
Please open a PR for fixing the docs as per your findings.
