### ISSUE TITLE
Add ability to create filter collections.

### ISSUE THREAD

**Issue by ADmad** [FriendsOfCake/search#224]
Refs https://github.com/FriendsOfCake/search/pull/221#issuecomment-392539097 by @burzum.

A follow up PR that will add `FilterCollection`. I want to get the huge declaration of a filter collection out of my table objects.

So instead of having this:

```php
	public function configureSearch() : void {
		$this->searchManager()
			->add('id', 'Search.Value', [
				'field' => [$this->aliasField('id')],
			])
			->add('title', 'Search.Like', [
				'field' => [$this->aliasField('title')],
				'before' => true,
				'after' => true
			])
			->add('organizer', 'Search.Like', [
				'field' => [$this->aliasField('organizer')],
				'before' => true,
				'after' => true
			])
			->add('start_date', 'Search.Compare', [
				'field' => [$this->aliasField('start_date')],
				'operator' => '>='
			])
			->add('end_date', 'Search.Compare', [
				'field' => [$this->aliasField('end_date')],
				'operator' => '<='
			]);
	}
```

I want this:

```php
$this->addBehavior('Search.Search', 'defaultFilterCollection' => new MyCollection());
```

Or that:

```php
$this->searchManager()->setCollection('default', new MyCollection());
```

I also dislike the two-level array approach used in the manager. It's a collection of collections on the first level and then a collection of filters. This should be refactored.

**Comment by ADmad** [comment]
Really like this idea. I think we can do even better  and avoid configuring the behavior/manager before hand.

It should not be difficult to have an implementation such that if the collection name specified in `find()` options does not exist then the search `Manager` looks for matching collection class (in `App\Model\Filter\) and instantiates it.

**Comment by burzum** [comment]
@ADmad get my other PRs merged and I'll finish this! Hurry, hurry! 😛

**Comment by burzum** [comment]
PR is open https://github.com/FriendsOfCake/search/pull/228
