### ISSUE TITLE
How Do I remove this 

### ISSUE THREAD

**Issue by zakblacki** [FriendsOfCake/search#226]
Please HELP !
Fatal error: Uncaught InvalidArgumentException: The plugin class `Search\Plugin` cannot be found. Ensure your autoloader is correct. in C:\xampp\htdocs\intellix\vendor\cakephp\cakephp\src\Http\BaseApplication.php:127 Stack trace: #0 C:\xampp\htdocs\intellix\vendor\cakephp\cakephp\src\Http\BaseApplication.php(95): Cake\Http\BaseApplication->makePlugin('Search\\Plugin', Array) #1 C:\xampp\htdocs\intellix\src\Application.php(36): Cake\Http\BaseApplication->addPlugin('Search') #2 C:\xampp\htdocs\intellix\vendor\cakephp\cakephp\src\Http\Server.php(121): App\Application->bootstrap() #3 C:\xampp\htdocs\intellix\vendor\cakephp\cakephp\src\Http\Server.php(82): Cake\Http\Server->bootstrap() #4 C:\xampp\htdocs\intellix\webroot\index.php(40): Cake\Http\Server->run() #5 {main} thrown in C:\xampp\htdocs\intellix\vendor\cakephp\cakephp\src\Http\BaseApplication.php on line 127

**Comment by ADmad** [comment]
This is an issue tracker not a help forum. Please use one of CakePHP's help forums for support.
