### ISSUE TITLE
Make addPlugin available

### ISSUE THREAD

**Issue by bond-kaneko** [FriendsOfCake/search#227]
I Attempted to install according to READEME.md. But I got an error.

```
Fatal error: Uncaught InvalidArgumentException: The plugin class `Search\Plugin` cannot be found. Ensure your autoloader is correct. 
in /var/www/html/Piyo/vendor/cakephp/cakephp/src/Http/BaseApplication.php:127 Stack trace: #0
 /var/www/html/Piyo/vendor/cakephp/cakephp/src/Http/BaseApplication.php(95): 
Cake\Http\BaseApplication->makePlugin('Search\\Plugin', Array) #1 
/var/www/html/Piyo/src/Application.php(36): Cake\Http\BaseApplication->addPlugin('Search') #2
 /var/www/html/Piyo/vendor/cakephp/cakephp/src/Http/Server.php(121): App\Application->bootstrap()#3
 /var/www/html/Piyo/vendor/cakephp/cakephp/src/Http/Server.php(82): Cake\Http\Server->bootstrap() #4
 /var/www/html/Piyo/webroot/index.php(40): Cake\Http\Server->run() #5 {main} thrown in /var/www/html/Piyo/vendor/cakephp/cakephp/src/Http/BaseApplication.php on line 127
```

 In versions above Cake 3.6.0, ```./bin/cake plugin load Search``` modifie bootstrap() like below.
```
public function bootstrap()
    {
        
        $this->addPlugin('Search');

        // Call parent to load bootstrap from files.
        parent::bootstrap();
    }
```

But it cause error. Because search has not `src/Plugin.php`. Are there plans to addPlugin() available?

versions:
CakePHP 3.6.3
search 4.4

**Comment by ADmad** [comment]
Can you try commenting out the line `addPlugin()` call? Since the plugin doesn't have routes or bootstrap file just class auto loading provided by composer should be enough.

**Comment by bond-kaneko** [comment]
@ADmad 
Yes, I commented out the `addPlugin()` then error cured. 
Is `addPlugin()` due to command `./bin/cake plugin load Search`? If so, I think that it would be better to edit README.md.
I am sorry if it was due to my operation.

**Comment by ADmad** [comment]
> Yes, I commented out the addPlugin() then error cured.

I am confused. Did commented `appPlugin()` call fix the problem or cause another error?

> Is addPlugin() due to command ./bin/cake plugin load Search? If so, I think that it would be better to edit README.md.

Yes it's the `./bin/cake plugin load Search` call which modified your `Application::bootstrap()` method and added the `$this->addPlugin('Search');` statement.

I'll think over the best course of action, whether to add a `Plugin` class to the plugin or update the readme.

**Comment by bond-kaneko** [comment]
Sorry, My English is not fluent enough. Remuving the `addPlugin()` call fix the problem.

> I'll think over the best course of action, whether to add a Plugin class to the plugin or update the readme.

Thank you for your response.
