### ISSUE TITLE
Persistent search??

### ISSUE THREAD

**Issue by seyfcom** [FriendsOfCake/search#230]
Hello,
First of all, thank you, great component!

I have that search on index, but when I go on a view and come back, i lose the search. I tried your queryStringWhitelist but i'm not I understood what it was. Anyway it doesn't change anything for me...

How can you achieve this?

**Comment by ADmad** [comment]
There's no inbuilt way to persist search params for your use case. You will have to implement it yourself using session.

**Comment by seyfcom** [comment]
ok I thought so and tried but did not succed... i don't get how to get to value back in the search form and that in the controller they use it too... if you have any hint... thanks
