### ISSUE TITLE
Extend 'Search.Like' feature when concatenating conditions

### ISSUE THREAD

**Issue by rkhe** [FriendsOfCake/search#239]
Is it possible to extend the "Search.Like" feature with OR operator when concatenating one or more conditions.

Currently in Like.php line 76, the `andWhere` is hard-coded and would like to be able to use `orWhere` operator:
`$this->getQuery()->andWhere([$this->getConfig('fieldMode') => $conditions], $colTypes);

**Comment by ADmad** [comment]
`Query::orWhere()` is deprecated so any patch using that won't be accepted :slightly_smiling_face:.

Also the `fieldMode` and `valueMode` options are already set to `OR` so not sure what you want.

**Comment by rkhe** [comment]
What I'm trying to do is having both `Search.Like` and `Search.Callback` generated in one query statement. I noticed that when doing that the `Search.Callback` query will be added first append by the `Search.Like` query.

Example:
**Search.Callback (with alwaysRun => true)**
$query->where(['id'=>13]); // additional query
**Search.Like**
just the same setup/config from the examples.

Query Result:
SELECT
...
FROM sometable tbl
WHERE (
tbl.id = 13 AND
(tbl.subject LIKE '%13%' OR tbl.description LIKE '%13%' OR tbl.notes LIKE '%13%')
) LIMIT 10 OFFSET 0

I need `OR` instead of `AND` next to `tbl.id = 13` statement.

**Comment by rkhe** [comment]
Sorry, mistake on my end. 
Was able to make it work by adding the `Search.Like` first then the `Search.Callback` then the Callback query will be added on the end. Though I still use the `Query::orWhere()` not sure how to use `Query::where()`. 

Thanks a lot.
