### ISSUE TITLE
Can you make search fields optional?

### ISSUE THREAD

**Issue by davidyell** [FriendsOfCake/search#24]
**Scenario**
I have a blog with posts, tags and categories. A post doesn't have to be in a category. My filter form includes a `like` match for the `title`, and a dropdown of categories with `'empty' => true`, using a `value` match on `category_id`.

**Generated url possibilities**
`example.com/posts?q=welcome` - Return posts containing 'welcome'
`example.com/posts?q=welcome&category=8` - Return posts in category 8 with welcome in the title
`example.com/posts?q=welcome&category=` - Returns no results

**Sidestep**
So far the only way I can find to sidestep this is to use a `custom` find and check the `$options` array param for `empty()` and ignore it if it's empty.

**Ideally**
The CakeDC/search had a nice way of just marking a filter field as allowed to be optional, which would exclude it from searches if it was empty. Something like this would be ideal for scenarios where you want to filter using optionally null data.

**Comment by jippi** [comment]
seems like a easy fix - check the value for empty and allowEmpty and don't append it to the query

**Comment by davidyell** [comment]
Thanks guys! :+1:
