### ISSUE TITLE
Separating search terms by space

### ISSUE THREAD

**Issue by Ali1** [FriendsOfCake/search#247]
Fab work!

I'm wondering - it's for a users model where there's a first name and surname. It'd be handy if I could put "Jo Smi" and find John (first name field) Smith (surname). Helps when trying to get peoples name over the phone and spelling is an issue.

Anyone got something like this to work? I'm thinking need to explode the search query and run it round.

PS: Even better if it can also find rows where the Smith could be a middle name (first name: John Smith surname: Andrews).

**Comment by dereuromark** [comment]
This is already available using multiValueSeparator
In our case we use:

    ->like('search', ['field' => ['first', 'second'], 'multiValueSeparator' => ' ', 'fieldMode' => 'AND']);

It checks that all the concat words in your search are at least matching to one field.

**Comment by Ali1** [comment]
```
SELECT 
  Patients.id AS `Patients__id`, 
  Patients.first_name AS `Patients__first_name`, 
  Patients.surname AS `Patients__surname`, 
FROM 
  patients Patients 
WHERE 
  (
    Patients.first_name like 'Jo Sm%' 
    OR Patients.surname like 'Jo Sm%'
  ) OR   (
    Patients.first_name like 'Jo%' 
    AND Patients.surname like 'Sm%'
  )
```
Basically could it generate this query.

**Comment by dereuromark** [comment]
Maybe you can help improving the documentation here, to display this use case there.

**Comment by Ali1** [comment]
```
WHERE 
  (
    (
      Patients.first_name like 'Jo%' 
      OR Patients.first_name like 'Sm%'
    ) 
    AND (
      Patients.surname like 'Jo%' 
      OR Patients.surname like 'Sm%'
    )
  )
```
Not quite what I had in mind since this would also match Jo Jo and I'd need have to keep this first query running to find spaces within fields e.g. first name "Jo Smith". But that's good enough for my needs! Thanks.

**Comment by dereuromark** [comment]
If you can come up with a way to do it the way you want, make a PR :)
But you need to also be able to formalize this as config somehow.
You can probably already solve it using a custom finder and some logic.

**Comment by Ali1** [comment]
Yep I think I'll come back to this and dig deeper for a clean solution. Thanks for your help :)

In the first instance, fixing "Joan Johnson" as a result for q:"Jo Sm"  should be easy enough!

**Comment by ADmad** [comment]
For the example shown in https://github.com/FriendsOfCake/search/issues/247#issuecomment-467949569 the conditions
```
(
    Patients.first_name like 'Jo Sm%' 
    OR Patients.surname like 'Jo Sm%'
  )
```
are redundant as any record matching those conditions will also match the conditions
```
(
      Patients.surname like 'Jo%' 
      OR Patients.surname like 'Sm%'
    )
```.

An update to expand the documentation is welcome. Closing the issue meanwhile.
