### ISSUE TITLE
Allow modify query before applying filter

### ISSUE THREAD

**Issue by raul338** [FriendsOfCake/search#249]
I have to search by an associated column, so I used a like, but sometimes the query doesn't have the join to search, resulting in a bad sql.
I propose add this callable to keep with the filter instead of manipulating the query in every place that calls the search finder, the callable should be called before calling process()

```php
// In ArticlesTable
$manager->like('author', [
    'field' => [
        'Authors.name',
    ],
    'before' => true,
    'after' => true,
    'wildcardAny' => '*',
    'wildcardOne' => '?',
    // this will be added, maybe called beforeProccess
    'beforeFilter' => function ($query, $filter) {
        $query->leftJoinWith('Authors');
    }
]);
```

**Comment by ADmad** [comment]
I don't want to add any more complexity to existing filters. 

You should just add additional functionality by extending the `LikeFilter` and making your own.

**Comment by dereuromark** [comment]
Depends on if this is for all (base) filters or only for Like.
The latter could be custom, but if this should go into all as opt-in we might have to support this in the plugin right?

**Comment by raul338** [comment]
Yes I thought to make a PR to make it in the base filter if you agree, since this could match for value filters for example.

**Comment by dereuromark** [comment]
You can make a PR to easier discuss options.
Doesnt have to ship with tests yet then.

**Comment by dereuromark** [comment]
PR open.
