### ISSUE TITLE
Enhancement or bug: Validator is not being triggered

### ISSUE THREAD

**Issue by TheMiller2015** [FriendsOfCake/search#255]
Hello.

I am using cake rest api with friendsofcake/crud and friendsofcake/search. Maybe, I forgot sth. to add, but I noticed at least in my setup, that all search-queries don't go through the table validator. 

Imagine a given model with the properties (and table coloums) "firstOccurence" and "lastOccurence". This model has a validator of nonNegativeInteger on both fields. 

When these fields are queried, it would be nice to run the user input (search query parameters) through the validator and to populate any error messages in case of validation errors. Right now, the search query is executed as is, which also could be dangerous. 

I digged in the code and found validate() in Search\Model\Filter\Base but it seems not to be used. Can you tell me if I did sth wrong (and what to improve) | my finding is a real enhancement | the validation-code is started but bot finished | this really is a bug.

I think, this is really important and it is totally okay to use the model-validator, since the model represents the database coloums and we are quering the database. Otherwise, we have to always create a callback and within this callback we have to duplicate the validator of the model and run through this).

Thanks in advance

**Comment by ADmad** [comment]
Yes the `Base::validate()` method is currently unused. Providing validation support was probably planned but never implemented.

You are welcome to submit a concrete proposal or open a pull request for that same.

**Comment by TheMiller2015** [comment]
Thanks. I'll try to find time and dig into this issue. When I'm successful, I'll open a pr. I think, this is kinda important to prevent security issues. But I can't promise that I'll be done with it in the next days/weeks.

**Comment by dereuromark** [comment]
@TheMiller2015 ping

**Comment by ADmad** [comment]
I am not sure if handling validation in the search filters is necessary. One can just use the `Form` class for their search form and set validations for that. The reason why `Filter\Base::validate()` exists is because it predates the addition of `Form` class to the core.

**Comment by ADmad** [comment]
Closing as we don't have any plans right now to add validation for filters. The unused methods `Base::validate()` and `Base::valid()` will be removed in next major.
