### ISSUE TITLE
Search triggers an error when used with Authorization plugin

### ISSUE THREAD

**Issue by alexvanniel** [FriendsOfCake/search#258]
When I perform a Search (submit the search form) while the Authorization plugin is active and loaded, I get the "The request to `xxxxxxx` did not apply any authorization checks.".
However, in the controller action the first thing that is handled is the authorization.

Does the Search (or maybe Search.Prg) do a redirect while searching and handling events and thus skipping the Authorization procedure? Or is there something I overlooked while configuring the Search plugin that is known to conflict with Authorization in combination with Search?

Ofcourse there is an option to skip authorization but that should not be necessary and far from secure.

**Comment by ADmad** [comment]
The "R" in PRG is for redirect :slightly_smiling_face:. But it's to the same URL with additional query string. There's nothing else which would interfere with Authorization.

**Comment by alexvanniel** [comment]
Yeah... I totally did not see that in the documentation even though it is there and written quite clearly even. I also figured that the R would stand for Redirect. Sorry for my brain fart.
It appears however that for some reason the Authorization middleware prevents the Prg plugin to redirect. The Authorization middleware will stop execution because it did not perform an authorize($model, $action) before the process was completed (which would be the actual redirect). So basically I am looking for a way to add authorize($model, $action) just before the Prg plugin redirects the user.

**Comment by alexvanniel** [comment]
I think I found something that seems to work. When i add authorize() to the controllers beforeFilter method I prevent the middleware from failing authorization. I'd need to limit this to only those action the Prg plugin acts upon... Although it does feel a bit dirty.
I admit, this is not strictly a Search.Prg issue, but is triggered by it like the Security component can be triggered as per documentation if you do not specify the exception in there.
