### ISSUE TITLE
Custom Filter was not found

### ISSUE THREAD

**Issue by BrunyC** [FriendsOfCake/search#259]
Im trying use Custom Filter im my project. I created a Filter folder in src/model with Compare.php file inside. But when i call $this->searchManager()->add('id', 'Compare'); in my ArticlesTables.php I got this error: "Search filter \"Compare\" was not found.",

Someone know why??

**Comment by dereuromark** [comment]
Where did you put your custom Compare class?
https://github.com/FriendsOfCake/search/tree/master/src/Model/Filter
Did you use a similar namespace locally?

Sounds like a developer error to me.

**Comment by BrunyC** [comment]
I did my Compare file like yours for make a test. So its exactly the same thing.

I put in app in App\Model\Filter like the documentation says. 

Give a Look;

<?php

namespace App\Model\Filter;

use Cake\Datasource\Exception\InvalidArgumentException;

class CompareFilter extends \Search\Model\Filter\Base
{
    protected $_defaultConfig = [
        'operator' => '>=',
        'mode' => 'AND',
    ];
   
    protected $_operators = [
        '>=', '<=', '<', '>',
    ];

    public function process()
    {
        debug($this->getQuery());exit;
        $conditions = [];
        if (!in_array($this->getConfig('operator'), $this->_operators, true)) {
            throw new InvalidArgumentException(sprintf(
                'The operator %s is invalid!',
                $this->getConfig('operator')
            ));
        }
        $value = $this->value();
        if (!is_scalar($value)) {
            return false;
        }
        foreach ($this->fields() as $field) {
            $left = $field . ' ' . $this->getConfig('operator');
            $conditions[] = [$left => $value];
        }
        
        $this->getQuery()->andWhere([$this->getConfig('mode') => $conditions]);

        return true;
    }
}

Is the same code just for test. I will change the code later, but first I need fix this error

**Comment by BrunyC** [comment]
I did my Compare file like yours for make a test. So its exactly the same thing.

I put in app in App\Model\Filter like the documentation says.

Give a Look;

<?php

namespace App\Model\Filter;

use Cake\Datasource\Exception\InvalidArgumentException;

class CompareFilter extends \Search\Model\Filter\Base
{
    protected $_defaultConfig = [
        'operator' => '>=',
        'mode' => 'AND',
    ];
   
    protected $_operators = [
        '>=', '<=', '<', '>',
    ];

    public function process()
    {
        //code here
    }
}

**Comment by BrunyC** [comment]
I did my Compare file like yours for make a test. So its exactly the same thing.

I put in app in App\Model\Filter like the documentation says.

Give a Look;

protected $_defaultConfig = ['..'];
protected $_operators = ['..'];

public function process() { //code here } }

**Comment by dereuromark** [comment]
What does your filter content/code look like?

**Comment by BrunyC** [comment]
I did my Compare file like yours for make a test. So its exactly the same thing.

I put in app in App\Model\Filter like the documentation says.

Give a Look;

<?php
namespace App\Model\Filter;
use Cake\Datasource\Exception\InvalidArgumentException;

class CompareFilter extends \Search\Model\Filter\Base
{
   protected $_defaultConfig = ['..'];
   protected $_operators = ['..'];

  public function process() { //code here } }
}

**Comment by BrunyC** [comment]
My Compare class its in src/model/filter/compare.php

use Cake\Datasource\Exception\InvalidArgumentException;

class CompareFilter extends \Search\Model\Filter\Base
{
    protected $_defaultConfig = [ 'operator' => '>=', 'mode' => 'AND'];
    protected $_operators = ['>=', '<=', '<', '>'];

 public function process() 
  { //code here }
}

Im calling in my ArticlesTables like:

$this->searchManager()->add('id', 'Compare');

**Comment by dereuromark** [comment]
You need to use case sensitive valid path elements, so model/filter/compare must be Model/Filter/Compare as documented.
Many things in PHP are case sensitive.

I don't think this is a bug. This is a bug tracker. For help on (Cake)PHP please refer to the slack channel or help forum.

**Comment by BrunyC** [comment]
I dont think this is a bug too. Its something Im forgetting. I just write im lower case, but in my code its in case sensitive mode. I will search for help in forum, thanks for help.
