### ISSUE TITLE
Stable 4.x release

### ISSUE THREAD

**Issue by dereuromark** [FriendsOfCake/search#266]
it might be time now to switch the branches and start a 4.x compatible stable tag

What is left to be done?

- [x] Check if (return) typehints are missing on public API etc
- [ ] master + release

**Comment by dereuromark** [comment]
We should do the typehints now:
- https://github.com/FriendsOfCake/search/blob/master/src/Model/Filter/Escaper/EscaperInterface.php#L13
- https://github.com/FriendsOfCake/search/blob/master/src/Processor.php#L32
- https://github.com/FriendsOfCake/search/blob/master/src/Model/Filter/Base.php#L182

etc

afterwards It is too late

**Comment by ADmad** [comment]
You should check the `cake-4.x` branch instead of `master` :).

**Comment by dereuromark** [comment]
I wonder if we should move away from the `__invoke` magic, to a more speaking and clear interface?
Similar to what happened from PSR middleware 1 vs 2

**Comment by ADmad** [comment]
We could rename `Base::__invoke()` to `Base::execute()`

**Comment by jadb** [comment]
Refs #277

**Comment by dereuromark** [comment]
Is https://github.com/FriendsOfCake/search/compare/tests?expand=1 still relevant?

**Comment by dereuromark** [comment]
So we make another RC first

I already updated my sandbox ( https://sandbox.dereuromark.de/sandbox/search-examples ) to the master branch now.

**Comment by dereuromark** [comment]
I recommend adding a wiki home entry similar to e.g. https://github.com/dereuromark/cakephp-test-helper/wiki
And link from the READMEs there, this way things can be handled more "Single source of truth" across multiple branches and core versions.

**Comment by andraskende** [comment]
Could you update the the 3.x branch install command on the README.

php composer.phar require friendsofcake/search ???

Thanks !!

**Comment by dereuromark** [comment]
The command always can to be adjusted as per needs of projects.
It will still work for Cake3 apps, as composer will auto detect the right version applicable. So nothing has to change here.

**Comment by dereuromark** [comment]
Are we ready to tag a stable version here?
I bet some of us, including me, so far tested this and it works as it did in 3.x.

**Comment by ADmad** [comment]
I'll do a stable release this weekend.
