### ISSUE TITLE
`Base::field()` and 'field` filter config.

### ISSUE THREAD

**Issue by ADmad** [FriendsOfCake/search#269]
The `Base::field()` method has been marked as deprecated since a while so I indent to remove it in 6.0 (new Cake 4 compatible major).

Correspondingly for consistency I would also like to rename the `field` config to `fields`. We can keep a check for old key name an throw exception to avoid silent error for those upgrading and then remove the check in 6.1.

**Comment by dereuromark** [comment]
Now is the time to cleanup, yeah :)
