### ISSUE TITLE
Add a helper to generate search form

### ISSUE THREAD

**Issue by curtisgibby** [FriendsOfCake/search#27]
I wrote a helper that automagically creates a complete search form based on the table's `searchConfiguration()` fields. I think it would be useful to include in this plugin.

``` php
use Cake\View\Helper;
use Cake\ORM\TableRegistry;

/**
 * SearchForm helper
 */
class SearchFormHelper extends Helper
{

    public $helpers = ['Form', 'Html'];

    /**
     * Default configuration.
     *
     * @var array
     */
    protected $_defaultConfig = [];

    /**
     * Output a complete search form, based on the search configurations set up
     * in the specified table
     *
     * @param $model string The Table to load
     * @return null|string An formatted FORM with inputs.
     */
    public function form($model)
    {
        $table = TableRegistry::get($model);

        // make sure the table has the behavior and has implemented the searchConfiguration method
        if (
            ! $table->behaviors()->has('Search') ||
            ! method_exists($table, 'searchConfiguration')
        ) {
            return null;
        }

        $searchConfig = $table->searchConfiguration()->all();

        $output = $this->Html->tag('h3', __('Search'));
        $output .= $this->Form->create();

        foreach ($searchConfig as $object) {
            $config = $object->config();

            // you can add stuff like `'multiple' => true` or `'empty' => ' '`
            // to the individual searchConfiguration field calls to be passed to
            // the form input
            $output .= $this->Form->input($config['name'], $config);
        }

        $output .= $this->Form->submit();
        $output .= $this->Form->end();

        return $output;
    }
}
```

The helper is loaded into the view, as normal, and is called in the template like this

``` php
<?= $this->SearchForm->form('Articles') ?>
```

(or if you want to be lazy, and copy-paste the same thing in all of your templates, you can call it like this)

``` php
<?= $this->SearchForm->form($this->request->params['controller']) ?>
```

![search-form](https://cloud.githubusercontent.com/assets/1086964/9124663/364f97be-3c56-11e5-98e3-8ea927c01812.png)

**Comment by jippi** [comment]
Looks good

Can you please pull-request it proper ?

**Comment by curtisgibby** [comment]
Sure, I can do that. Before I do, do you know of a way to pass the Table object through from the Controller to the View to the Helper? I felt kind of dirty instantiating a new copy of the Table in the Helper in order to get its `searchConfiguration` settings.

**Comment by vnt** [comment]
The helper works with version 3.1?
I tried, but the form to the search is not generated.

**Comment by curtisgibby** [comment]
I'm currently using this form helper on a 3.1 app.

**Comment by vnt** [comment]
I do not understand! The search form is not generated.
 I have insert the helper in /src/View/Helper/SearchFormHelper.php
I have add namespace App\View\Helper;   to avoid the error: Create the class SearchFormHelper below in file: src/View/Helper/SearchFormHelper.php
<?php
namespace App\View\Helper;
use Cake\View\Helper;
use Cake\ORM\TableRegistry;

class SearchFormHelper extends Helper
{
    public $helpers = ['Form', 'Html'];
....

In template index.cpt
I have insert
<?= $this->SearchForm->form($this->request->params['controller']) ?>

**Comment by dereuromark** [comment]
Any update here?

**Comment by burzum** [comment]
@dereuromark Can we close this?
