### ISSUE TITLE
search for CONCAT

### ISSUE THREAD

**Issue by btaens** [FriendsOfCake/search#28]
Hello,
I have the age old issue of trying to search a user's full name. With this plugin, I'm trying to do it as so:
```php
$search
            ->like('search', [
                'before' => true,
                'after' => true,
                'field' => [
                    $this->aliasField('username'),
                    "CONCAT(" . $this->aliasField('last_name') . ", ' ', " . $this->aliasField('first_name') . ")",
                ],
            ]);
```

The problem is, in the SQL query it becomes:
CONCAT(
      `Users`.`last_name`, ' ', `users`.`first_name`
    ) like '%name%'

For some reason, it always removes capitalization from the second `Users`, and therefore throws an SQLSTATE[42S22]: Column not found error.

**Comment by burzum** [comment]
I think you'll need to use an expression. See http://book.cakephp.org/3.0/en/orm/query-builder.html#selecting-data If this doesn't work I guess you'll have to create your own custom type.

**Comment by ADmad** [comment]
You can just use the `callback` type filter and modify query as required using an expression for CONCAT() fragment.
