### ISSUE TITLE
beforeProcess option

### ISSUE THREAD

**Issue by irongomme** [FriendsOfCake/search#283]
I've tried beforeProcess option with a like operation, but it seems to have no effects. After trying to search it in the plugins code, i haven't found anything about this options. 

So, is it really implemented ?

**Comment by ADmad** [comment]
https://github.com/FriendsOfCake/search/blob/cc1c500a80f1a8d6c3bb3ec90cfe33bd2bfb1733/tests/TestCase/Model/Filter/BaseTest.php#L260-L320
