### ISSUE TITLE
searchManager default vs admin etc

### ISSUE THREAD

**Issue by dereuromark** [FriendsOfCake/search#284]
Config often looks like:
```php
	/**
	 * @return \Search\Manager
	 */
	public function searchManager() {
		/** @var \Search\Manager $searchManager */
		$searchManager = $this->behaviors()->Search->searchManager();

		$searchManager
			->like('username', [
				'before' => true,
				'after' => true,
			])
			->value('country_id');

		return $searchManager;
	}
```

But what if I don't want to allow the frontend user the access to username filter, only to country.
Right now this is a bit hard to filter to allow only the Admin/Users controller access to this.

Should we add similar to https://book.cakephp.org/4/en/orm/validation.html#creating-a-default-validation-set

    public function searchManagerAdmin() {}

etc, and a config value for the component as `'validator'` (defaulting to default)?

Or is there a different/better way to create scopes?

One could inject the scope as arg:

        public function searchManagerAdmin($scope = 'default') {}

This would allow the dev to use logic or protected methods inside of it.

**Comment by ADmad** [comment]
I am not in favour of adding more ways of setting up filters from within table classes, it makes them too bloated.

One can already use filter collections for having different sets of filters for frontend and backend. Creating your own [fillter collections](https://github.com/FriendsOfCake/search/tree/master/docs#filter-collection-classes) is lot more cleaner.

**Comment by dereuromark** [comment]
Hm, could be almost a bit overkill for a simple field toggle on/off
What if the component can have a white or blacklist of search fields that can then be adjusted as per controller's needs?

**Comment by dereuromark** [comment]
I guess when collections extend themselves it might be not that big of a deal probably.
Fair enough then. I will check if this works as expected.
