### ISSUE TITLE
Additional search data from request to manager

### ISSUE THREAD

**Issue by dereuromark** [FriendsOfCake/search#285]
I have been transforming some Table code into FilterCollection classes.
I also tried to put some of the custom finders from the controller level into that class.
But that doesn't seem to work in all cases.

Currently, I am using this https://github.com/dereuromark/cakephp-geo/blob/master/docs/Behavior/Geocoder.md#pagination-and-distance

When transforming that now, the additional data becomes an issue as we cannot set up joined rules it seems.
So basically, distance is the query param here, but I also need `'lat' => 13.3, 'lng' => 19.2` to be passed into that callback. But right now there seems to be no way other than some hacks - like adding them as query params with "void" callbacks and trying to fetch them inside the distance one as well.

Are there are ideas on how to use more than one field for certain callbacks - and especially without the need to send them through query data if not necessarily needed?

**Comment by ADmad** [comment]
We could allow setting a fields whitelist for `Processor` similar to the empty values list it has.

**Comment by dereuromark** [comment]
For now I abandoned that refactoring and keep the custom finders here in the controller, small overhead here, so that's ok for now.

PS: can you please open a wiki page entry for me, so I can enter the version map?
If all plugins do that, we have less confusion about what versions are what cake core and PHP min etc.

**Comment by ADmad** [comment]
> PS: can you please open a wiki page entry for me

I have enabled wiki.

**Comment by dereuromark** [comment]
https://github.com/FriendsOfCake/search/wiki#version-map exists now

I am OK closing this here for now.
