### ISSUE TITLE
Query parameter value filter containing period in string name is not running

### ISSUE THREAD

**Issue by jadelbe418** [FriendsOfCake/search#292]
I am currently using example similar to the first 2 listed here to grab search filters:

```
class ExampleCollection extends Search\Model\Filter\FilterCollection
{
   public function initialize()
    { 
       // 1. Filters when present
       $this->value('name', [
            'multiValue' => true,
            'multiValueSeparator' => ',',
            'mode' => 'AND',
            'field' => 'name',
        ]);

       // 2. Does not filter when present
       $this->value('example.type_id', [
            'multiValue' => true,
            'multiValueSeparator' => ',',
            'mode' => 'AND',
            'field' => 'Example.type_id',
        ]);
 
       // 3. Filters when present
       $this->value('type_id', [
            'multiValue' => true,
            'multiValueSeparator' => ',',
            'mode' => 'AND',
            'field' => 'Example.type_id',
        ]);
   }
}
```
The first value call of value your works and the second does not. For some reason FreidndsOfCake/Search is not recognizing uri parameters containing a period, like 'example.type_id'. 

Is this a bug or by design? Or am I missing some piece of configuration needed to do this?

**Comment by ADmad** [comment]
Using dot separated names for the search fields is not supported. There's no need for your search form names to exactly match for db files and/or associations. Just rename the field to say `example_type`.

**Comment by jadelbe418** [comment]
Well it breaks the conventions used in my application to not include the dot so no mention of what certain characters being off limits in the docs. But I can work around it if that is what we need to do. Thanks.

**Comment by ADmad** [comment]
> Also there is no mention of certain characters being off limits in the docs.

There's no special mention as it's default Cake behavior that a dot in field name generates an array. It's not something special in the plugin. `example.type_id` will give you HTML input with name `example[type_id]`.

**Comment by jadelbe418** [comment]
That makes sense. I did not know that about Cake. Thanks!
