### ISSUE TITLE
Bake filter collections?

### ISSUE THREAD

**Issue by dereuromark** [FriendsOfCake/search#296]
Do we want to add a bake task to easily generate filter collection classes?

With basic fields of scalar value added into as 
- string: like()
- key or int: value()

E.g.
```php
namespace App\Model\Filter;

use Search\Model\Filter\FilterCollection;

class ProfilesFilterCollection extends FilterCollection
{
    /**
     * @return void
     */
    public function initialize(): void
    {
        $this->like('title')
            ->value('country_id')
            ...;
    }
}
```

As it is easy to just remove a few lines, but it would be nice to have them generated.

We should also only add visible fields of the entity.

**Comment by ADmad** [comment]
Sure, having such a bake task can't hurt.

**Comment by dereuromark** [comment]
(Admin) prefixed ones would go into

> /Filter/Admin/...

Or how would you handle them?
