### ISSUE TITLE
warning with bake in cake42

### ISSUE THREAD

**Issue by luizcmarin** [FriendsOfCake/search#297]
![image](https://user-images.githubusercontent.com/67489841/98117881-195fe580-1e89-11eb-8d08-a39a4ca3e2c6.png)

deprecation error when generating bake application.

**Comment by dereuromark** [comment]
Can you open a PR with the suggested changes, please?

bear in mind that this can also create a barrier as a constraint update to that new minor is then required.
so all has its pros and cons
https://github.com/FriendsOfCake/search/blob/master/composer.json#L25 => will become ^4.1 then

**Comment by luizcmarin** [comment]
Every VENDOR plugin must be updated to keep the entire product in perfect working condition.
I request the update of the plugin to adapt to the new changes in cakephp 4.2.
In particular, get the use of getTable for Table, as shown in the image and quotes
https://book.cakephp.org/4.next/en/appendices/4-2-migration-guide.html#orm

**Comment by ADmad** [comment]
@luizcmarin Thanks for the reporting this. CakePHP 4.2 is no where close to a stable release, so there's no cause for alarm about a deprecation notice.

The issue will be addressed in due time, meanwhile you can continue trying 4.2 without any problem.
