### ISSUE TITLE
Remove csrfToken in PrgComponent

### ISSUE THREAD

**Issue by steefaan** [FriendsOfCake/search#30]
Do you think it would make sense to remove the `_csrfToken` in the `PrgComponent`? In general it's not necessary but it would keep the URL clean. What do you think? If you agree I will create a PR.

**Comment by ADmad** [comment]
Yup removing `_csrfToken` would be nice.

**Comment by ADmad** [comment]
This is no longer an issue as core itself remove `_csrfToken` after checking.
