### ISSUE TITLE
Search.Prg killing request data

### ISSUE THREAD

**Issue by davidyell** [FriendsOfCake/search#31]
**What I did**
Added the `Search.Prg` component to my `AppController`.

**What I expected to happen**
I could save an edit form and the data would be saved and updated.

**What actually happened**
The form said it saved, yet no change to the data occurred.

**How I fixed it**
I removed the `Search.Prg` component and my form saved and updated as expected.

**What I think the problem is**
https://github.com/FriendsOfCake/search/blob/master/src/Controller/Component/PrgComponent.php#L20
An edit action is `put`, so this will wipe out the request data.

**Comment by dereuromark** [comment]
You could probably just check on put or post (and maybe even patch) here.
Basically !get :)

**Comment by ADmad** [comment]
This is why the example code in readme shows to load the component only for index action :wink:

**Comment by ADmad** [comment]
Querystring is set to `request->data` so that the search form is populated with existing search terms. IMO this is just a matter of improving the docs.

**Comment by davidyell** [comment]
This also kills the delete method if it's active in the controller, as it redirects the request meaning your delete is `get`, so the `allowMethods` call fails.
