### ISSUE TITLE
Search resetUrl function 

### ISSUE THREAD

**Issue by rudy1976s** [FriendsOfCake/search#314]
I have search collection  with associated record search.
The collection is like the following:
```
$this->add('q', 'Search.Like', [
            'before' => true,
            'after' => true,
            'fieldMode' => 'OR',
            'comparison' => 'LIKE',
            'wildcardAny' => '*',
            'wildcardOne' => '?',
            'fields' => ['Carts.no', 'Carts.serial','Carts.sell_to_customer_name','Carts.sales_subject'],
        ])
        ->value('Customers.no');
```

The query generated is like the following:

`...carts?Customers%5Bno%5D=C00011`

The resetUrl is not able to remove the key from the querystring because it is an array.
I have added the following code to make it work :

`$query = Hash::flatten($query,'.');`

just after 

`$searchParams = (array)$this->_View->get('_searchParams');`

Is there a better method to achieve the same result ?

Rudy

**Comment by ADmad** [comment]
You are not supposed aliased values for the 1st argument of the search methods. So use `->value('no')` instead of `->value('Customers.no')`.

**Comment by rudy1976s** [comment]
Without the alias on my side the search no longer  works because the Customers is not the actual table but one of the associated to the Carts table ( in this case belongsTo)

**Comment by ADmad** [comment]
Then use the `fields` option to specify the aliased name `->value('no',  ['fields' => ['Customers.no'])`

**Comment by dereuromark** [comment]
Should we maybe trigger an error or even exception if someone uses a dot in the key? With a helpful message?
That might make it easier to understand.

**Comment by ADmad** [comment]
While an error message would be helpful I don't want to add an additional `strpos()` check for every field in the collection. We could just add a note/warning in the readme instead and see if the issue crops up again.

**Comment by rudy1976s** [comment]
I have tried with fields parameter but the query still gives me no result. Perhaps there is something else which breaks
