### ISSUE TITLE
Passing an integer value to the search query

### ISSUE THREAD

**Issue by rkhe** [FriendsOfCake/search#321]
Hi, 

This is more likely a wish list item and not sure if there's a workaround to do this. 

Currently, the `Search.Like` works with string columns only. If we try to add an integer column field say a "seat_number" column it throws an error at `[CORE\src\Database\Type\IntegerType.php]` with message `Cannot convert value of type string to integer`. 
This is due to the $value being checked (is_numeric) is `"%10%"` where `10` is the value passed from the query string.

It would be nice to consolidate the IntegerType data on the `Search.Like` filter.

**Comment by dereuromark** [comment]
Maybe this helps: https://github.com/FriendsOfCake/search/issues/218

**Comment by rkhe** [comment]
This is amazing! 
I just added `'colType' => ['seat_number' => 'string'],` and it works! 

Thanks a lot @dereuromark
