### ISSUE TITLE
German umlauts not recognized

### ISSUE THREAD

**Issue by wikosoft** [FriendsOfCake/search#327]
Hello,
we're having an issue where when we use the search to search an entry in the DB that contains German umlauts (äöü) and it doesn't return results. Otherwise, the search works fine, just not when using the umlauts. The documentation says nothing about this, and I'm not sure how to deal with it. This is our search code:

        $this->searchManager()

            ->add('q', 'Search.Callback', [

                'callback' => function ($query, $args, $filter) {

                    $query->where(['OR' => ['Contacts.email LIKE' => '%'.$args['q'].'%','Contacts.display_name' => '%'.$args['q'].'%']])->distinct(['Contacts.email']);
                }
            ]
        ); `

**Comment by dereuromark** [comment]
You need to provide the DB scheme/collation you are using.
This is not really a plugin issue, more a DB one.
You are most likely using an invalid or not fitting collation and therefore dont get results.

**Comment by wikosoft** [comment]
Hello dereuromark! First, thanks for the fast response. I am also a big fan of your work and appreciate all that you have done for cakePHP.
The Kollation for the contacts table in the DB is set to: utf8_general_ci

**Comment by dereuromark** [comment]
I usually use unicode_ci
Not sure if that behaves differently

**Comment by wikosoft** [comment]
The error was here:
`
'Contacts.display_name' => '%'.$args['q'].'%']])`

The fix was just adding a LIKE, so it looks like:

`'Contacts.display_name LIKE' => '%'.$args['q'].'%']])`
