### ISSUE TITLE
BC issue

### ISSUE THREAD

**Issue by dereuromark** [FriendsOfCake/search#329]
https://github.com/FriendsOfCake/search/pull/320 seems to be not fully BC
Controllers are now broken in projects that update to latest plugin version

> You must provide an $alias or set the $defaultTable property.

loadModel() didnt need an argument
fetchTable() now does, ot should default to the default model (`$defaultTable`) of the controller here.
It just is not available via public API it seems, so the component cannot access it.

Could we use reflection to shim this?

**Comment by ADmad** [comment]
`$defaultTable` does get set to the same values as `$modelClass` https://github.com/cakephp/cakephp/blob/bae80000d28106aaf7bca509db02b556340f3ea2/src/Controller/Controller.php#L222

Have you explicitly set the `$modelClass` property in the controller?

**Comment by dereuromark** [comment]
No, since this was not needed
having to do so now would need to touch thousands of controllers. thats not ideal.

**Comment by ADmad** [comment]
Not saying you need to do that. Just trying to figure what could be causing the problem. As shown in the code linked above `$defaultTable` should already have a value set through the controller's constructor, so I don't see how/why you get that error.

**Comment by dereuromark** [comment]
Interesting, could that project have maybe a missing parent call on any specific controller callback? I will check.
The linked PR fixed it though for us.

**Comment by dereuromark** [comment]
OK, all AppController and specific controller callbacks call parent in the first line.
That cannot be it.

**Comment by ADmad** [comment]
Let's 1st figure out why the error is occurring before patching the code.

The property gets set in the constructor itself so what callbacks do isn't relevant. Have you overridden the controller's constructor?

**Comment by dereuromark** [comment]
No, only initialize()
```php
    public function initialize(): void
    {
        parent::initialize();

        $this->loadComponent('RequestHandler');
        ...
}
```

**Comment by ADmad** [comment]
What does `debug($this->defaultTable)` in `initialize()` give you?

**Comment by dereuromark** [comment]
It is null, but modelClass is set

Also here it is null in Core Controller
```
        if ($this->defaultTable !== null) {
            $this->modelClass = $this->defaultTable;
        }
```

Where is $defaultTable supposed to be "set"?

**Comment by dereuromark** [comment]
I think I understand the issue
The project does not specify any defaultTable (neither should it need to) in any controller, so only modelClass is set in Controller in core
As such it can never have it populated later since it is never written to.

**Comment by ADmad** [comment]
> It is null, but modelClass is set

Then I bet you have explicitly set `$modelClass` in the controller. Because if `$modelClass` is not set then the controller's constructor sets both `$modelClass` as well as `$defaultTable`.

Are you using the latest 4.x release?

**Comment by dereuromark** [comment]
Oh great, 4.3.0-RC3 for some reason the legacy project is not able to update further
That might be the issue then, let me check.

**Comment by ADmad** [comment]
No wonder you have the problem :) You need [this](https://github.com/cakephp/cakephp/commit/7a5b5cfd8483f4ed9fcd5c9b7420ea1e0c873d5f) fix which is available since `4.3.2`.

**Comment by dereuromark** [comment]
Stupid me then, sry for the bother

**Comment by ADmad** [comment]
Now worries, always better to investigate the cause first rather than going for a fix :)
