### ISSUE TITLE
Reset doesn't work WA's solution to keep search filters

### ISSUE THREAD

**Issue by berarma** [FriendsOfCake/search#331]
I'm using [World-Architects' solution](https://github.com/World-Architects/cakephp-query-param-preserver) to preserve the search parameters while navigating.  It works well but the reset button no longer works.

To fix it, I need to add `preserve=0` to the query string of the reset link, but `resetLink` and `resetUrl` don't allow passing query parameters. The solution is simple, creating my own links or copying these methods and modifying them.

I want to propose that these methods accept additional query parameters.

**Comment by dereuromark** [comment]
Can you make a PR with your needed or suggested changes?

**Comment by berarma** [comment]
While working on this PR I've realized it would be easier to call `resetUrl`, modify the returned URL and create the link.

Thanks @dereuromark.
