### ISSUE TITLE
belongsToMany Search not Working

### ISSUE THREAD

**Issue by rctoris** [FriendsOfCake/search#337]
I have a model named Recipes. There is a `belongsToMany`  relation for tags defined as followed:

```php
$this->belongsToMany('Tags', [
    'foreignKey' => 'recipe_id',
    'targetForeignKey' => 'tag_id',
    'joinTable' => 'recipes_tags',
    'dependent' => true,
]);
```

I'm trying to search for recipies that have their own title, body, or assocatied tags using the `beforeProcess` and `fields`. This is what I have:

```php
$this->searchManager()
    ->like('q', [
        'before' => true,
        'after' => true,
        'fieldMode' => 'OR',
        'comparison' => 'ILIKE',
        'wildcardAny' => '*',
        'wildcardOne' => '?',
        'fields' => ['title', 'body', 'Tags.title'],
        'beforeProcess' => function (SelectQuery $query, array $args, Base $filter): void {
            $query->contain('Tags');
        },
    ]);
```

I get the following error:

`SQLSTATE[42P01]: Undefined table: 7 ERROR: missing FROM-clause entry for table "tags" LINE 1: ...ecipes.title ILIKE $1 OR Recipes.body ILIKE $2 OR Tags.title... ^`

Removing `'Tags.title'` removes all errors so the contain clause is working. 

I replaced `Tags` with a `belongsTo` relation (e.g., users (author)), and the search works correctly.

**Comment by dereuromark** [comment]
You might want to check how the tags plugin uses the search plugin for habtm search:
https://github.com/dereuromark/cakephp-tags/tree/master/docs#searchfilter
Maybe it can give some insights

**Comment by rctoris** [comment]
Seems close but that's providing `tag` information in the form. I want to find recipes dynamically with the query, not from a form field.

**Comment by dereuromark** [comment]
The custom finder can be used either way, no form needed :)

**Comment by ADmad** [comment]
Containing a belongs to many association doesn't generate a SQL join, so your error is expected. Look up the CakePHP docs or ask on the support forums for how to generate the query you need, then use the `callback` filter to achieve the same.

**Comment by rctoris** [comment]
Less than helpful hint but I will look elsewhere. Thanks @dereuromark for some pointers.
