### ISSUE TITLE
5.x: Search exception

### ISSUE THREAD

**Issue by dereuromark** [FriendsOfCake/search#338]
I have params of 

    'city_id' => (int) 76,

Which then triggers exception

> Search\Model\Filter\Base::passedValue(): Return value must be of type array|string|null, int returned
```php
    /**
     * @return array|string|null
     */
    protected function passedValue(): string|array|null
```

I wonder if this should be also allowing other scalar values actually?
As it seems hard to control the exact types going into the search here IMO

**Comment by dereuromark** [comment]
I worked around it for now by casting

    $search['city_id'] = (string)$city->id;

before passing those further on.

**Comment by ADmad** [comment]
How/why is `city_id` an `int`?  Passed values normally come request query string which are always strings.

**Comment by dereuromark** [comment]
The data doesnt completely come from the request, thats why
It seems strange to have to take a primary key int, make it string only to become int afterwards again, though.

**Comment by ADmad** [comment]
If we are going to widen the type then let's just make it `mixed` instead of limit to scalars and array. This value is eventually going to be used in a query which does accept various types of objects depending on the field type. Also `Base::value()` which calls `passedValue()` already has `mixed` return type.

**Comment by dereuromark** [comment]
Turns out, the wrapping method already expects mixed.

    /**
     * Get the value of the "name" from HTTP GET arguments.
     *
     * @return mixed
     */
    public function value(): mixed
    {
        $value = $this->_config['defaultValue'];

        $passedValue = $this->passedValue();
        if ($passedValue === null) {
            return $value;
        }

        return $passedValue;
    }
    
So, yeah, mixed is the correct way to go
