### ISSUE TITLE
Ability to alias a finder in the url

### ISSUE THREAD

**Issue by davidyell** [FriendsOfCake/search#36]
`example.com/index?availability=1`

```php
$search->finder('state');
```

How would I map my `availability` url param to my `findState` finder? Is this possible? I know from the docs you can use `aliasField` but I can't see a way to alias a finder.

**Comment by ADmad** [comment]
```php
$search
        ->finder('availability', [
            'finder' => 'state'
        ])
```

**Comment by davidyell** [comment]
Ah fair enough, I didn't see that in this code.

https://github.com/FriendsOfCake/search/blob/master/src/Type/Finder.php#L30
