### ISSUE TITLE
Search after pagination sort 

### ISSUE THREAD

**Issue by Wouter0100** [FriendsOfCake/search#42]
When I open a new page (without a querystring) and sorts the content using `PaginatorHelper::sort`, it's being sorted fine. But when I now search something, the params of the sort are being removed from the querystring at the redirect stage (in the POST the URL querystring is still there).

I've updated `$request->params['pass']` to `$request->query` in [PrgComponent](https://github.com/FriendsOfCake/search/blob/fe9f82c7cc971c0c4c60b5c93774bb226dcb75c9/src/Controller/Component/PrgComponent.php#L25), which seems to work. But I'm not sure if this is the right fix.

**Comment by ADmad** [comment]
If you removed `$request->params['pass']` passed params will be lost so you need to preserve both.
