### ISSUE TITLE
Add namespace prefix FoC

### ISSUE THREAD

**Issue by burzum** [FriendsOfCake/search#47]
I have the problem that we have a more or less huge application which was using the CakeDC search plugin initially. Due to the fact that *both* are using the `Search` namespace I'm getting a problem by loading both plugins side by side.

Can't we prefix the namespace of the plugin? Sure I could fork it and change it, but this is a good example of why vendor namespaces are useful.

**Comment by jippi** [comment]
wait, you could also prefix the namespace of the cakedc version ? :)

**Comment by burzum** [comment]
FoC is already slow, but the CDC moves even a lot slower. See the ton of open issues and PR's for their search plugin. :)

**Comment by dakota** [comment]
:-1: for breaking any existing application.

**Comment by jippi** [comment]
FoC is community, its really fast when changes are straight forward and make sense :)

CDC got paid employees :) 

I dislike the change, we don't vendor namespace, and mixing two search plugins in one app seems weird, since they basically do the same thing in different ways

**Comment by burzum** [comment]
@dakota tag it 2.0 then? Upgrading is just a matter of adding the vendor in 3 places: bootstrap, component loading, behavior loading.

@jippi When I don't ask somebody and push for it usually nothing happens for weeks. The CDC got paid employees yes, but doesn't maintain their plugins very well. Just take a look at the issues. Open source doesn't seem to pay out for them so it's not a priority.

Yes, it is strange but I would prefer to use the FoC plugin over the bloated CDC search plugin because the FoC search does the same with 1/4 of the code and has a better architecture. But the app is right now still using the CDC plugin and migration can't be done within a day and I would prefer to run them side by side and do it as I work through the model layer.
