### ISSUE TITLE
Simplify the find('search') call

### ISSUE THREAD

**Issue by burzum** [FriendsOfCake/search#53]
Why do I have to explicitly call `filterParams()` here?

```php
->find('search', $this->Articles->filterParams($this->request->query))
```

I would move the call of `filterParams()` inside the behaviors [findSearch()](https://github.com/FriendsOfCake/search/blob/master/src/Model/Behavior/SearchBehavior.php#L46) method. If desired it can be still made configurable. This would remove the need to add the filterParams() call manually in the controller.

Another thing I don't think that is ideal is this inside findSearch():

```php
        if (isset($options['search'])) {
            $options = $options['search'];
        }
```

I would prefix the `search` with an `_` like the core does it with _serialize, _ext and a few others as well. Because `search` is a term that is likely to get used in a filter form.

**Comment by dereuromark** [comment]
+100 on the second part. 

About the first, how do you pass in the query strings into the behavior then for the filterParams() call?

**Comment by burzum** [comment]
@dereuromark well, simply without wrapping the query with the method? :)

```php
->find('search', $this->Articles->filterParams($this->request->query))
// vs
->find('search', $this->request->query)
```

**Comment by dereuromark** [comment]
Ah, now I got it :)
I wonder if you ever needed the non filtered version. But it sounds reasonable to me to change it.

**Comment by burzum** [comment]
> I wonder if you ever needed the non filtered (or custom filtered?) version.

Me too. I would always apply it by default and give the option to disable it for whatever possible reason.

**Comment by davidyell** [comment]
These changes sound good to me :+1:

**Comment by ADmad** [comment]
> ->find('search', $this->request->query)

Will cause bad things to happen if query string contains other valid find options like `group` etc.

**Comment by ADmad** [comment]
Closing as related PR is open.
