### ISSUE TITLE
Feedback / RFC: Setup / Docs

### ISSUE THREAD

**Issue by ionas** [FriendsOfCake/search#56]
I got some issues setting up search:

1. For search to work like in the docs one must composer require dev-master. require friendsofcake/search will get you 1.1 which will not work with the new configuration way.

2. As for an example how to reference an exact value this is what to do:
```php
        $this->searchManager()
            ->add('id', 'Search.Value', [
                'field' => $this->aliasField('id'),
            ]);
```
If you don't specify field and do not use ```aliasField()``` you might get ambiguity errors in SQL queries
The example utilizing 'field' hashkey however suggests that it takes an array of fieldnames. This is not the case for Search.Value. Is this intentional? Is this a bug? Generates a query like ```WHERE Array IN (:c0)``` with the error "Notice (8): Array to string conversion [CORE/src/Database/Expression/Comparison.php, line 136]"

It seems, @hmic experienced similar issues for 1. and 2. implementing/integration search. Onces these issues are cleared it runs like a charm (for now ;)

Questions:
* Should I change the docs to reflect that dev-master is requried (interim) - how would the composer command look (I changed the composer.json and ran compser update)?
* Should I change the docs adding the above code snipplet (set to your articles example)?

**Comment by hmic** [comment]
+1

**Comment by ADmad** [comment]
> Should I change the docs to reflect that dev-master is requried (interim) - how would the composer command look (I changed the composer.json and ran compser update)?

`php composer.phar require friendsofcake/search:dev-master`

> Should I change the docs adding the above code snipplet (set to your articles example)?

You can update existing example for `author_id` to used aliased field name.

> The example utilizing 'field' hashkey however suggests that it takes an array of fieldnames. This is not the case for Search.Value. Is this intentional? Is this a bug? 

A PR is welcome to update `Value` filter to also allow using multiple fields similar to `Like` and `Compare`.

**Comment by simkimsia** [comment]
Are the docs even hosted on readthedocs.org or anywhere else? I cannot seem to find it.

**Comment by ADmad** [comment]
Closing as the README has been significantly improved since.
