### ISSUE TITLE
[Question] Does the search require POST or GET request?

### ISSUE THREAD

**Issue by simkimsia** [FriendsOfCake/search#61]
I have set up this way

I have a `CompaniesController` under the namespace `App\Controller\Api`
like this:
```
class CompaniesController extends AppController
{

    public $components = [
        'Crud.Crud' => [
            'actions' => [
                'Crud.Index',
                'Crud.Add',
                'Crud.Edit',
                'Crud.View',
                'Crud.Delete',
            ],
            'listeners' => [
                'Crud.Api',
                'Crud.RelatedModels',
                'Crud.Search',
            ],
        ]
    ];
    /**
     * Index method
     *
     * @return void
     */
    public function index()
    {
        if (in_array($this->request->action, ['index', 'lookup'])) {
            $this->loadComponent('Search.Prg');
        }

        $this->Crud->on('beforePaginate', function(Event $event) {
            $this->paginate['conditions']['tessi_account_id'] = 2;
        });
        return $this->Crud->execute();
    }
```

My routes are:

```
Router::defaultRouteClass('DashedRoute');

Router::extensions(['json']);

// for prefix api
Router::prefix('api', function ($routes) {
    // All routes here will be prefixed with `/api`
    // And have the prefix => api route element added.
    $routes->resources('Companies');
    $routes->fallbacks('InflectedRoute');
});
```

since `Search.Prg` is used, does this mean I **must** use `POST` on `/api/companies/index?q=abc`?

What is the **ideal** way to proper do a search via API?

1. GET or POST request ?
2. the paramter q should be a query parameter or a form parameter?
3. Should the url be `/api/companies/index` or simply `/api/companies`?

Note that I am also using crud plugin. If I should post this question in the crud repo, let me know and I will move this issue there.

**Comment by bravo-kernel** [comment]
I bet someone will point you to other places for your questions since this is not a help-forum but since it's almost christmas...
- GET
- query parameter
- simply /api/companies

**Comment by simkimsia** [comment]
Then what's the point of a Prg? Isn't Prg means PostRedirectGet? So shouldn't I start with a POST?

**Comment by dereuromark** [comment]
@simkimsia You only need a POST first if you are submitting a form to a non-query string location to *build* a query string one. The PRG patter is only needed when posting first, thus the logical conclusion is easy here:  If you connect to a API right away using query strings, there is no need to post first. 

As to your URL question: companies and companies/index are the same, and using query strings it still doesnt matter which one you prefer, I personally prefer the shorter/simpler one :)

**Comment by simkimsia** [comment]
@dereuromark said:

> ..  if you are submitting a form to a non-query string location to build a query string one. 

Sorry, what is "a non-query string location to build a query string one"? Can you give an example, please?

**Comment by dereuromark** [comment]
Almost, yes. Please see how the plugin usually works in normal production mode where PRG is used.
That will answer this question fully.
