### ISSUE TITLE
Filtering ZIP/POST code not work

### ISSUE THREAD

**Issue by salines** [FriendsOfCake/search#62]
I implement this plugin and everything works great (full names, location, job titles), except for the filtering zip / post code that contain a combination of letters and numbers, example: BL6 2TZ

If I put in the filter only letters (BL) or numbers (6), plugin return results.

How to solve this problem?

```
<?= $this->Form->input('zipcode',['class' => 'form-control','label' => 'Postcode / Zipcode']); ?>

//
        $this->searchManager()
            ->add('name', 'Search.Like', [
                'before' => true,
                'after' => true,
                'field' => [$this->aliasField('name')]
            ])
            ->add('job_title', 'Search.Like', [
                'before' => false,
                'after' => true,
                'field' => [$this->aliasField('job_title')]
            ])
            ->add('location', 'Search.Like', [
                'before' => false,
                'after' => true,
                'field' => [$this->aliasField('city')]
            ])
            ->add('zipcode', 'Search.Like', [
                'before' => true,
                'after' => true,
                'field' => [$this->aliasField('zipcode')]
            ])
            ->add('country', 'Search.Like', [
                'before' => false,
                'after' => true,
                'field' => [$this->aliasField('country')]
            ]);


```

**Comment by ADmad** [comment]
How exactly is it not working? What's the sql generated for the "not working" case?

**Comment by salines** [comment]
Candidates.zipcode like '%BL6 2TZ%'

**Comment by ADmad** [comment]
Don't see anything wrong with that sql fragment. You are probably don't have any records which matches that condition or misunderstanding how LIKE works.

**Comment by salines** [comment]
Ops, sorry, You are correct. 

This entry exist in the database, but for users under different rolls. Thank you again for this great plugin. Happy New Year.
