### ISSUE TITLE
Find matching

### ISSUE THREAD

**Issue by aiphee** [FriendsOfCake/search#63]
I'm not sure if it is possible now or not, but i don't see it in documentation.

I need search by associated models, like this:

```PHP
$this->ContentPages->find()->contain(['Tags'])->matching('Tags', function ($q) {
                return $q->where(['Tags.name' => 'test']);
            })
```

Is it possible? If not, would be possible to add it?

Thank you.

**Comment by davidyell** [comment]
You would just specify the `finder` you want to use in the `searchConfiguration` method.

**Comment by ADmad** [comment]
You can use `callback` type and modify the query in callback function as required.

**Comment by curtisgibby** [comment]
It might be helpful to have an example of this in the documentation. I found this issue by searching for "matching" in the repo's issues, but others might not be so persistent in trying to find this info.
