### ISSUE TITLE
[QUESTION] Regarding initialize() & beforeFilter()

### ISSUE THREAD

**Issue by Spriz** [FriendsOfCake/search#65]
Could anyone elaborate on this one? https://github.com/FriendsOfCake/search/blame/master/README.md#L153 :smile:

**Comment by davidyell** [comment]
It's really just where you are loading the plugin. The main issue is that if you don't specify the actions the `PrgComponent` runs on, it will wipe out all your form data, which will break your `add` and `edit` forms.
