### ISSUE TITLE
[QUESTION] Breaking the parameter to search for more words in one input

### ISSUE THREAD

**Issue by vdevenancio** [FriendsOfCake/search#76]
I'm using this plugin for my search needs in CakePHP and I think it's really awesome, but I'm having trouble when the search uses more than one word. I'd like to know if there's an easy solution that breaks the parameter to search individually for them. 

For example, "test1 test2" searches only for the whole string. I'd like to search for "test1" and "test2" independently.

**Comment by ADmad** [comment]
Use the 'callback' type and manipulate the query as needed.
