### ISSUE TITLE
Multiple values

### ISSUE THREAD

**Issue by glafarge** [FriendsOfCake/search#77]
What do you think about the support of multiple values ?

For example, if i need the following configuration : 

```php
$this->addBehavior('Search.Search');
$this->searchManager()
    ->add('place', 'Search.Like', [
        'before'=>true,
        'after'=>true,
        'field' => [$this->aliasField('ZipCode'), $this->aliasField('City')]
]);
```

As the Like filter only supports single value, I have created a child filter to supports arrays.

```php
namespace App\Model\Filter;

use Cake\ORM\Query;

class LikeMultiple extends \Search\Model\Filter\Like
{

    /**
     * Process a LIKE condition ($x LIKE $y).
     * Allow multiple values
     *
     * @return void
     */
    public function process()
    {
        if ($this->skip()) {
            return;
        }

        $conditions = [];
        foreach ($this->fields() as $field) {
            $left = $field . ' ' . $this->config('comparison');

            if(is_array($this->value())) {
                foreach($this->value() as $value) {
                    $right = $this->_wildCards($value);
                    $conditions[] = [$left => $right];
                }
            }
            else {
                $right = $this->_wildCards($this->value());
                $conditions[] = [$left => $right];
            }
        }

        $this->query()->andWhere([$this->config('mode') => $conditions]);
    }
}
```

I think we can add this functionnality to Like filter directly. This can be extended to Compare too.
I can make a PR if needed.

What do you think about it and about security concerns ?

**Comment by burzum** [comment]
> What do you think about the support of multiple values ?

Good idea.

But IMO it should be a method in the base class or a trait. I can see that you might want to use multiple values with an IN, but in another place you want to do an AND or an OR.

A param that can take N values should have a flag like `multiValue => true`.

**Comment by glafarge** [comment]
What you suggest is to add functionality to Like base class, add a new boolean parameter to it named `multiValue`. So, we can deal with multiple values and avoid conflicts with IN filter when needed to. 
Right ?

**Comment by burzum** [comment]
No.

1. The functionality should be optional
2. The feature should be easy to use by *any* filter
3. There should be some way to decide how to threat the multiple values (What you want to do with them)

So either make it a trait or the functionality can be implemented in https://github.com/FriendsOfCake/search/blob/master/src/Model/Filter/Base.php

**Comment by glafarge** [comment]
Good ideas ! Anyway it needs more work to implement it.
Thank you, I'll look at it.

**Comment by Mistermasque** [comment]
Hi,

I'm using this search behavior. But I can't submit exact values from a multiple select.
For example : Articles belongs to Users with the foreign key user_id in articles table.

I implement this code : 
```php
// In Model/Table/ArticlesTable.php
$this->addBehavior('Search.Search');
$this->searchManager()->value('user_id');
$this->searchManager()->like('title');
```

But when I submit data like this : 
`$user_id = ['1', '2']`

The behavior dismiss this value directly after this part of code in the function SearchBehavior::findsearch().
```php
$params = (array)$options['search'];
$params = Hash::flatten($params);
$params = array_intersect_key(Hash::filter($params), $filters);
```
In this configuration, creating a new Filter will be useless.

Actually, I'm using this code in my controller's action to build the complete where condition  : 
```php
$query = $this->Articles->find('search', ['search' => $this->request-data])

$params = array_intersect_key($this->request->data, array_flip(['user_id']));
		foreach ($params as $field => $values) {
			$query->andWhere(['Articles.' . $field . ' IN' => $values]);
		}
```
I think it would be much more elegant to construct all the query conditions inside the search behavior.

Is there a solution to deal with multiple values ?

Best regards

**Comment by dereuromark** [comment]
I am also interested a a good solution here for multiple values.
I like @burzum idea about the multipleValues flag and then using IN by default.
The only problem will be with empty values passed on as the ORM behaves strangely around those edge cases.

**Comment by doonot** [comment]
I would really appreciate it if the support of multiple values would make it into the official package. Thanks!

**Comment by dereuromark** [comment]
Did you just thumbs up your own comment :P Awesome
Well, maybe someone could start making a PR that we can then review.

**Comment by ndm2** [comment]
On a related note, why does the like filter currently try to handle array values?

https://github.com/FriendsOfCake/search/blob/2.1.0/src/Model/Filter/Like.php#L51-L57

Assuming that it's possible that an array value makes it in there in the first place, is this supported by the query builder at all? Wouldn't that condition just get discarded?

**Comment by ADmad** [comment]
@ndm2 Depending on the `mode` the array will get turned into a bunch of `OR` or `AND` conditions https://github.com/FriendsOfCake/search/blob/2.1.0/src/Model/Filter/Like.php#L40

**Comment by dereuromark** [comment]
@ndm2 So that is more for the fields than the values :)

**Comment by ndm2** [comment]
But it would nest `$right`, not `$conditions`, ie it would produce

```php
'field LIKE' => ['%value 1%', '%value 2%']
```

Does the query builder relly expand this to multiple conditioons? :confused:

**Comment by ADmad** [comment]
@ndm2 Good catch, it won't.

**Comment by ndm2** [comment]
Good good, that will make things easier... I need this functionality in a current project, so in case no one beats me to it, I'll give it a shot some day in the next week.

**Comment by ADmad** [comment]
Closing as related PR has been opened.
