### ISSUE TITLE
Proper LIKE syntax for wildcards

### ISSUE THREAD

**Issue by dereuromark** [FriendsOfCake/search#82]
I would like to see this plugin also handle the LIKE syntax better than currently,
similar to the former cakedc one ( https://github.com/CakeDC/search/blob/master/Model/Behavior/SearchableBehavior.php#L31-L32 )

Users do not expect the sql syntax, nor should the plugin directly expose this sql specific one IMO.
Usually - like search engines do - they abstract it into a meta language, in this case using the well known `*` for any and `?` for a specific single char.

This is especially important as right now, if you need to look for those specific `%` or `_` chars, you get a lot of false positives here, e.g. when trying to find all that contain `22% discount` etc, as those are not escaped either and directly enter the DB search as wildcards.

And if you ever need `*` and `?` to be searchable (more unlikely as the other ones), then this would be configurable so you can adjust it on project level to be different ones.

I would like to know if there is an interest in implementing this in this plugin (only in the Like class of course).
If so I could look into fixing that in the near future.

**Comment by jippi** [comment]
PR welcome
