### ISSUE TITLE
There should be a "isSearch" bool

### ISSUE THREAD

**Issue by dereuromark** [FriendsOfCake/search#84]
The CakeDC search has a bool flag "isSearch" to be [passed down to the view](https://github.com/CakeDC/search/blob/master/Controller/Component/PrgComponent.php#L250) so the form knows if a "reset" button or alike is needed.
This is currently not possible with this one.
You cannot just use !empty(querystring) because that could contain some order/page params etc.

Is there an idea on how to get this implemented?
Then I can take a look into this.

**Comment by dereuromark** [comment]
feedback?

**Comment by jippi** [comment]
PRG could append ?_isSearch=1 to the query when redirecting ? :)

**Comment by dereuromark** [comment]
That is not always true though, as sometimes it does not apply filters (like clearing or just using defaults again). So this would have to be done only for get request and only if any of the behavior's query modifications occur.
also in general it would be best to just have an internal variable passed down to be used in the view layer etc to toggle then.
The question is now this can be done.

**Comment by jippi** [comment]
considering we only got a model/table/behavior going for us, it would have to be through Configure to push the state, or up to the developer to just mark it on his own.

**Comment by burzum** [comment]
> PRG could append ?_isSearch=1 to the query when redirecting ? :)

The PRG component or behavior could detect if any searchable query param was present and implement a method `isSearch` that returns bool.

**Comment by htstudios** [comment]
It should take some kind of scope, if you have multiple filters per page.
The name should be configurable. By default something like `searching=true` or `searching[CountriesTable] = true` (latter with scopes).

**Comment by dereuromark** [comment]
If the component has a method for this, we don't necessarily need the query string approach.
Anyone a concrete idea how to implement?

**Comment by inoas** [comment]
How would you differentiate across different Cells?

**Comment by dereuromark** [comment]
@inoas This works on a query basis on the model layer, cells are out of scope here, you will need to do that yourself somehow.

**Comment by inoas** [comment]
I am not so sure its a good solution (as the boolean state that one really wants should store if a query/search had been executed, and as such that's hard to know from the model layer and should be in the controller layer where user interaction is handled best), but if it works for you guys, nvm.
