### ISSUE TITLE
Problems to install followiing the README

### ISSUE THREAD

**Issue by N3Wolf** [FriendsOfCake/search#88]
Hi, i am new to cakePHP, so this question is a beginner's one:

I installed CRUD and CRUD-view (nice work on that, by the way)

In the readme to install Search, it is told to configure the Table class
But what table class? I must create a new file in /src/Model/Table with the table name I want to apply the Search Plugin? or is it in vendor\cakephp\cakephp\src\ORM\Table.php ?

Also, is there any incompabilities with Crud and Crud-view?

**Comment by thinkingmedia** [comment]
The readme is referring to an existing Table class in your `src\Model\Table` folder. For example; if you have a database table called "Blogs" it would be the "BlogTable.php" file.

The Crud-View plugin was designed to only work with the Crud plugin. So there is no compatibility issues.

**Comment by N3Wolf** [comment]
Ok, i did it:


```
use Search\Manager;


class UsersTable extends Cake\ORM\Table {
    
    public function initialize(array $config)
    {
        parent::initialize();
        // Add the behaviour to your table
        $this->addBehavior('Search.Search');

    }
    // Configure how you want the search plugin to work with this table class
    public function searchConfiguration()
    {
        $search = new Manager($this);
        $search
            ->value('email', [
                'field' => $this->aliasField('email'),
            ])
            // Here we will alias the 'q' query param to search the `Users.email`
            // field and the `Users.rg` field, using a LIKE match, with `%`
            // both before and after.
            ->like('q', [
                'before' => true,
                'after' => true,
                'field' => [$this->aliasField('email'), $this->aliasField('rg')]
            ])
            ->callback('foo', [
                'callback' => function ($query, $args, $manager) {
                    // Modify $query as required
                }
            ]);

        return $search;
    }

}
```

But now i am getting the error:

> Unknown method "filterParams"
> BadMethodCallException

> ⟩ Cake\ORM\Table->__call
> APP/Controller\UsersController.php, line 42
> ⟩ App\Controller\UsersController->index
> [internal function]
> ⟩ call_user_func_array
> ROOT\vendor\friendsofcake\crud\src\Controller\ControllerTrait.php, line 51
> ⟩ App\Controller\AppController->invokeAction
> CORE\src\Routing\Dispatcher.php, line 114
> ⟩ Cake\Routing\Dispatcher->_invoke
> CORE\src\Routing\Dispatcher.php, line 87
> ⟩ Cake\Routing\Dispatcher->dispatch
> ROOT\webroot\index.php, line 36

**Comment by jippi** [comment]
Hi @N3Wolf

Thanks for your kind words.

Can you please use Slack / IRC / StackOverflow for support on how to use the project? I try to keep the issues at GH to bugs only, and it doesn't seem to be the case here. Feel free to drop a link in a comment to the SO post if you make one
