### ISSUE TITLE
RFC: Default action settings for the PRG component

### ISSUE THREAD

**Issue by burzum** [FriendsOfCake/search#89]
It is pretty annoying that by default the component is used for *all* actions. This can lead to funny issues and if you forgot about the Prg component, you'll have a nice "WTF?" moment when using actions with POST that are not supposed to use PRG.

IMHO it is wrong that the component makes use of PRG for *all* actions by default. It would be better if the user would have to specify them explicitly.

**Comment by dereuromark** [comment]
I agree.
https://github.com/FriendsOfCake/search/commit/1adecb98caa980a2b201c33b12ca898fccc42639 was already a step in the right direction. Just an empty array should be the default, though, IMO.
So you either manually set it to true or you specify the actions.
We can do this now with the major bump.
