### ISSUE TITLE
Release readme mismatch

### ISSUE THREAD

**Issue by davidyell** [FriendsOfCake/search#94]
Regression introduced in #92

Currently the readme has been changed, but the details provided in the new version are not compatible with the latest `1.2.4` release. 

So if like me you copy and paste from the readme into new projects, none of your code works until you figure out that you need the readme for the tag you're using.

Specifically, the change from `filterParams()` to `_search`

If it was me, I'd just do a new release with change notes and some guidance on what users of the plugin need to do to upgrade their application code.

**Comment by ADmad** [comment]
Fixed
